### ISSUE TITLE
Support instructions to install this version

### ISSUE THREAD

**Issue by ndjones** [foxyproxy/browser-extension#1]
Hi,
I've just come across FoxyProxy and see this new version emerging. Not sure if its ready for prime time - happy to be a tester 👍 
Perhaps some install from source instructions could be added to help.html? Or happy to wait for it to land in the Chrome store when ready.
thanks!
Nick

**Comment by erosman** [comment]
Thank you for your support. Once the code is ready, it will be made available for beta testing, before the final release (due by the end of the year).

**Comment by erosman** [comment]
@jpggithub The front page said that it is being updated for v3.
Anyway, the code has been uploaded to the repository.
Please note that it is beta for beta-testing only.

**Comment by jpggithub** [comment]
@erosman Yes, you're right, sorry.
I don’t know how I didn’t see it !:-/

**Comment by chromer030** [comment]
Any news on version 8 ?

**Comment by erosman** [comment]
> Any news on version 8 ?

It has been done.
Initial target was for Chrome but Chrome MV3 didn't have an authentication method. New process for authentication was added in Chrome 108.
The code was released here to get some feedback to eliminate any possible issues. However, the feedback has been limited (1 only).

**Comment by mjpieters** [comment]
> The code was released here to get some feedback to eliminate any possible issues. However, the feedback has been limited (1 only).

I do find it hard to find this version back when I go looking for it. I _love_ using it, even though I have to reinstall it each time my browser has restarted.

I am very much looking forward to this becoming an official release.

**Comment by erosman** [comment]
> I do find it hard to find this version back when I go looking for it. I _love_ using it, even though I have to reinstall it each time my browser has restarted.
> 
> I am very much looking forward to this becoming an official release.

@mjpieters Are you using v8.0 with Chrome or Firefox?
How long have you been using it?
Have you had any issues with it?

**Comment by mjpieters** [comment]
> Are you using v8.0 with Chrome or Firefox?

Both, Firefox 113 currently, on MacOS. 

> How long have you been using it?
 
Since the beginning of February, I filed a few issues at the time, see #16, #17.

> Have you had any issues with it?

Not since those two issues were handled, very quickly! I only have problems when Firefox has restarted and I forgot to re-install it. ;-)

**Comment by Darkcarnage23** [comment]
I been using this on firefox developer edition (115.0b9) and havent really seen much issues and i prefer using this over the other editions. 

The only way on release version to install the addon (at the moment) is via temporary addons but **if you're on Beta/nightly or dev edition you can go to ``about:config`` and set ``xpinstall.signatures.required`  to `false``**


How to install this addon:
1. download repo (or use git)
2. unzip the downloaded file
Firefox
1. go to src folder
2. select everything inside it and create a zip
4. rename zip to xpi
5. go to about:addons and import the addon from files 
Chrome
1.   on chrome make sure developer mode is on
2.  Load unpacked and select src folder

**Comment by erosman** [comment]
> Although for some reason the latest [version](https://github.com/foxyproxy/browser-extension/commit/8467947977f97d67569b44d26589e540a661cff2) was behaving strangely for me so i stuck with an older version

What is the issue?
We were planning to release this version as FoxyProxy Basic to get  some feedback, before releasing it fully.

**Comment by bam80** [comment]
What is the estimate for the release?
Will this work for FF mobile also?

**Comment by erosman** [comment]
> What is the estimate for the release?

The extension has been ready for a while. The delay is due to the lack of beta-testing.
The code was released here in the hope of getting some feedback.

> Will this work for FF mobile also?

It should work on FF mobile.

**Comment by bam80** [comment]
With install instructions, I think it has better chances to be added

**Comment by chromer030** [comment]
> The delay is due to the lack of beta-testing.
The code was released here in the hope of getting some feedback.

We are ready to test and feedback, please share us instructions to start.

**Comment by erosman** [comment]
The installation process was posted in https://github.com/foxyproxy/browser-extension/issues/1#issuecomment-1611238824

Here it is again:

- Backup your FoxyProxy settings
- Download repo 
  - [browser-extension](https://github.com/foxyproxy/browser-extension) -> Code (green button) -> Download ZIP
  - or use git
- Unzip the downloaded file
- **Firefox** *(Nightly/Beta/Developer Edition)*
  - Rename `manifest-firefox.json` in `src` folder to `manifest.json`
  - Go to `about:debugging#/runtime/this-firefox`
  - Click "Load Temporary Add-on..."
  - Select above `manifest.json`
- **Chrome**
  - Rename `manifest-chrome.json` in `src` folder to `manifest.json`
  - Go to `chrome://extensions/`
  - Enable Developer Mode (top right)
  - Click "Load Unpacked"
  - Select above `manifest.json` (or `src` folder)

**Comment by bam80** [comment]
@erosman thanks, don't you think it's better to repost it in the Readme to have more potential testers?

**Comment by bam80** [comment]
> Go to about:debugging#/runtime/this-firefox

@erosman this doesn't seem to work for FF Mobile. Any way to install there?

**Comment by erosman** [comment]
> this doesn't seem to work for FF Mobile. Any way to install there?

AFAIK, it is not  currently possible to install extensions directly in Firefox for Android.

More info: [Find and install Add-ons on Firefox for Android](https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android)

**Comment by ilyaigpetrov** [comment]
Hi, @erosman.

I see that `browser.proxy.settings` API is used in the sources.
Meanwhile this API hasn't been implemented on Android yet according to https://bugzilla.mozilla.org/show_bug.cgi?id=1725981.

Do you think the lack of this API will be a block for mobile FireFox?

**Comment by erosman** [comment]
You can now try installing [FoxyProxy Basic](https://addons.mozilla.org/firefox/addon/foxyproxy-basic/) on Firefox for Android.

**Comment by TriMoon** [comment]
> You can now try installing [FoxyProxy Basic](https://addons.mozilla.org/firefox/addon/foxyproxy-basic/) on Firefox for Android.

Keep in mind that the current version does not work properly yet, see: https://github.com/foxyproxy/firefox-extension/issues/158#issuecomment-1739064550

**Comment by chromer030** [comment]
I'm using version 8 on chrome and it's working great without any problem.

**Comment by erosman** [comment]
> I'm using version 8 on chrome and it's working great without any problem.

Thank you for the feedback.

**Comment by ericjung** [comment]
> I'm using version 8 on chrome and it's working great without any problem.

Are you using patterns? Or switching proxies without patterns?

**Comment by chromer030** [comment]
> Are you using patterns? Or switching proxies without patterns?

I have 8 PAC proxy, 2 Socks5, 1 HTTPS.
With simple patterns.

**Comment by TriMoon** [comment]
@chromer030 since you use Chrome, and i don't, can you please check https://github.com/foxyproxy/browser-extension/issues/31 to see if Chrome has same problem or not, so we can make sure it is Firefox only...

**Comment by erosman** [comment]
> Are you using patterns? Or switching proxies without patterns?

The bug in v8.0 relates to "Import from older versions" (and upgrading). It is fixed in v8.1.
There should be no issues with other operations in v8.0.
