### ISSUE TITLE
change background color

### ISSUE THREAD

**Issue by gmankab** [foxyproxy/browser-extension#100]
hello, can you please add ability to change background color from orange to just black or white

**Comment by erosman** [comment]
Which section's background color are you referring to?
Do you mean the background color of the buttons?

**Comment by gmankab** [comment]
i mean background color in all sections

not buttons

**Comment by erosman** [comment]
The background is not orange. Do you mean the dark chocolate color?

<img src="/foxyproxy/browser-extension/raw/main/screenshots/8.1/dark-theme/pattern-tester-tab.jpg" width="200" alt=""> 

<img src="/foxyproxy/browser-extension/raw/main/screenshots/8.1/light-theme/pattern-tester-tab.jpg" width="200" alt="">

**Comment by gmankab** [comment]
yes, i mean it

**Comment by erosman** [comment]
v8.9
- Added Theme feature

**Comment by gmankab** [comment]
thank you, waiting for 8.9 release
