### ISSUE TITLE
PAC mode doesn't work on firefox

### ISSUE THREAD

**Issue by 20NE** [foxyproxy/browser-extension#101]
foxyproxy basic 8.7
pac file can view in foxyproxy UI, but PAC mode doesn't work on firefox, log show it as well.
But basic 8.2 pac mode work on chrome.

**Comment by erosman** [comment]
> pac file can view in foxyproxy UI

View is a display feature only. It has no consequence in the setting of the PAC.

> but PAC mode doesn't work on firefox


- Is the toolbar icon in color (not grey)?
- Is FoxyProxy controlling the Network settings?
  Go to: **Firefox Settings -> Network Settings**
- When you set a PAC URL (not with Store Locally), does it show up in **Firefox Settings -> Network Settings -> Automatic proxy configuration URL**?

**Comment by 20NE** [comment]
> * Is the toolbar icon in color (not grey)?
yes.
> * Have you allowed "Run in Private Windows"?
no
> * Is FoxyProxy controlling the Network settings?
>   Check in: **Firefox Settings -> Network Settings**
no
> * When you set a PAC URL (not with Store Locally), does it show up in **Firefox Settings -> Network Settings -> Automatic proxy configuration URL**?
no

**Comment by erosman** [comment]
As mentioned in the Help:
> On Firefox, users must enable "Run in Private Windows", as it is required by Firefox for proxy settings
