### ISSUE TITLE
8.x on firefox does not respect network.dns.disableIPv6

### ISSUE THREAD

**Issue by bugfood** [foxyproxy/browser-extension#102]
Since the upgrade to FoxyProxy 8, firefox connects to sites using IPv6 even when `network.dns.disableIPv6` is `true`. Version 7.5.1 (and presumably other older versions) would use IPv4 or IPv6, depending on `network.dns.disableIPv6`.

Steps to reproduce:

1. Use a dual-stack host running firefox and a dual-stack proxy (via socks5 and maybe other protocols).
2. Install FoxyProxy 8 (currently 8.7).
3. Import the proxy, e.g. as `socks5://localhost:8801?title=test&proxyDns=false`
4. Enable the proxy.
5. Configure firefox to have `network.dns.disableIPv6` set to `true`.
6. Navigate to an IP-checker website, e.g. https://ifconfig.co/

Observed results:
The IP-checker website shows the client IP as an IPv6 IP.

Expected results:
The IP-checker website shows the client IP as an IPv4 IP.

Thanks,
Corey

**Comment by erosman** [comment]
There is nothing in the FoxyProxy code (v6-7 or v8) to select between IPv4 & IPv6. :thinking: 

BTW, I noticed an oversight in Import Proxy List which sets the Proxy DNS to `true`. (fixed in v8.9)
Try turning the Proxy to off in the proxy and see if that makes a difference.

**Comment by bugfood** [comment]
Thank you.
