### ISSUE TITLE
PAC mode doesn't work on firefox Android

### ISSUE THREAD

**Issue by rllbe** [foxyproxy/browser-extension#104]
The same pac url setting works for firefox windows, but not for firefox android
Browsers and extensions are all on latest versions

**Comment by erosman** [comment]
Pleas note from FoxyProxy Help:

> PAC URL (not available on Android)

Firefox for Android doesn't support [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings#browser_compatibility) API yet.
