### ISSUE TITLE
pattern editor should be at the top of the list

### ISSUE THREAD

**Issue by nvalexander** [foxyproxy/browser-extension#105]
Please make the pattern editor for new patterns more accessible.
Currently, when I add a pattern to a long list of patterns, the dialog box is needlessly located at the bottom of the list.
Worse, in order to scroll down to that dialog box, I have to drag down an extremely narrow box, which happens to sit next to all the buttons that delete patterns.

**Comment by erosman** [comment]
Adding a new pattern on top is possible but depends on how other users feel about it.

I have updated the UI so once a new pattern is added, the scroller scrolls to the end (bottom). (v8.9)
I have also made it to focus the "pattern" input.
Is that helpful?

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/8b05d55c-ea3c-4723-8701-a75da396402b)

**Comment by nvalexander** [comment]
Yes, it looks good.
