### ISSUE TITLE
"Proxy by Patterns" is only available when multiple proxies exist, disabling patterns for single proxy setups

### ISSUE THREAD

**Issue by lanmaster53** [foxyproxy/browser-extension#106]
Patterns only apply when "Proxy by Patterns" is enabled, which is only available when more than one proxies are configured. Therefore, it is no longer possible to filter a single proxy, even if it is configured with patterns. I recommend enabling the "Proxy by Patterns" option even when only a single proxy is configured, which was how v7.x worked.

**Comment by lanmaster53** [comment]
My temporary workaround is to create my "real" proxy with an **include all** pattern followed by **exclusion** patterns. I then create a "dummy" proxy with an **exclude all** pattern followed by a **dummy include** pattern. If there isn't an include pattern on each proxy, then the "Proxy by Patterns" option will not show up. After doing this, I can enable "Proxy by Patterns" and everything behaves as expected and can be validated by the log.

This was way too hard for something that was so simple before. As a fellow software developer, I don't understand all of these major changes to something that simply worked perfectly fine the way it was.

**Comment by erosman** [comment]
Can you explain a bit more?

The "Proxy by Patterns" option shows when there is at least ONE proxy with a pattern.


![image](https://github.com/foxyproxy/browser-extension/assets/6458876/b8eecc64-8031-4baa-8c6f-16bae4ae4470)

**Comment by lanmaster53** [comment]
Yep. I see that now.

Why does the option only exist if there is an include rule? Is there not an implicit include all? If not, why? Seems unintuitive. When I configure the proxy, it implicitly includes all. When I add a pattern, the proxy suddenly implicitly excludes all. This has not been the case historically and makes configuring one or more proxies with patterns confusing.

**Comment by erosman** [comment]
> Seems unintuitive. When I configure the proxy, it implicitly includes all. 

Many people would want to set a proxy for specific sites. That is what the patterns are there for.

> When I add a pattern, the proxy suddenly implicitly excludes all.

Whatever you include will be proxied and whatever you exclude wont.
The rest wont be proxied.

> This has not been the case historically and makes configuring one or more proxies with patterns confusing.

FoxyProxy 8 gives the choice and control to the user to set patterns to suit their needs. 


By definition. a pattern has to match something and that is whatever is in "include".

If you want to include all, there is an include all pattern.
- Add an include all
- Exclude whatever you want

If you are only using one proxy, and that is for all, there is a simpler way.
- Don't add any patterns
- Add the excludes to the Global Exclude
- Instead of "Proxy by Patterns", select that individual proxy

This way you will have 2 entries in the popup, "Disable" and the "proxy"

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/7b5ade0e-3632-474e-81cc-178c584bc4ee)

**Comment by lanmaster53** [comment]
> > Seems unintuitive. When I configure the proxy, it implicitly includes all.
> 
> Many people would want to set a proxy for specific sites. That is what the patterns are there for.
> 
> > When I add a pattern, the proxy suddenly implicitly excludes all.
> 
> Whatever you include will be proxied and whatever you exclude wont. The rest wont be proxied.
> 
> > This has not been the case historically and makes configuring one or more proxies with patterns confusing.
> 
> FoxyProxy 8 gives the choice and control to the user to set patterns to suit their needs.
> 
> By definition. a pattern has to match something and that is whatever is in "include".
> 
> If you want to include all, there is an include all pattern.
> 
> * Add an include all
> * Exclude whatever you want
> 
> If you are only using one proxy, and that is for all, there is a simpler way.
> 
> * Don't add any patterns
> * Add the excludes to the Global Exclude
> * Instead of "Proxy by Patterns", select that individual proxy
> 
> This way you will have 2 entries in the popup, "Disable" and the "proxy"
> 
> ![image](https://private-user-images.githubusercontent.com/6458876/293409715-7b5ade0e-3632-474e-81cc-178c584bc4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzgyMDIsIm5iZiI6MTcwMzg3NzkwMiwicGF0aCI6Ii82NDU4ODc2LzI5MzQwOTcxNS03YjVhZGUwZS0zNjMyLTQ3NGUtODFjYy0xNzhjNTg0YmM0ZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTkyNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDgwZTUwOTE4Y2ZiMjY5ZjE0N2E3M2EyYWYzYTA0ZWI4YTljNDYwYWIzYzFjY2RjM2QyMGU1NmZiYjNjYzJkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cuDPx3bx32FPqDrpJ813rOyyPogZgBLpWYcBPlO3OVY)

This looks like a decent solution. Do Global Excludes officially support wildcards? According to my testing they do, but I want to confirm. What about regex?

**Comment by erosman** [comment]
> This looks like a decent solution. Do Global Excludes officially support wildcards? According to my testing they do, but I want to confirm.

They do but there are considerations. You can read about them in the include **Help** under **Global Exclude**.
Please note that the implementation is based on the browser passthrough/bypass list rules.


> What about regex?

As bowsers don't support Regex in passthrough/bypass list, it is not supported.

**Comment by lanmaster53** [comment]
Got it. The documentation isn't clear on wildcards at the end of URLs, such as for the TLD. How will an exclusion like `*.example.*` work as a global exclusion?

**Comment by erosman** [comment]
> The documentation isn't clear on wildcards at the end of URLs, such as for the TLD. How will an exclusion like *.example.* work as a global exclusion?

It is not supported.

There are links in the Help to Chrome & Firefox documentation for the supported formats e.g. [No Proxy for](https://www-archive.mozilla.org/quality/networking/docs/aboutno_proxy_for)
