### ISSUE TITLE
Can't use my old patterns file with new version

### ISSUE THREAD

**Issue by Nishantbhagat57** [foxyproxy/browser-extension#108]
Since the last update I can't use my pattens file with this newer version:
https://raw.githubusercontent.com/Nishantbhagat57/OK-VPS/main/foxyproxyBB.json

What I did:
Import > Import from older versions > selected foxyproxyBB.json

But, No "Pass through" patterns are added.

![Screenshot 2024-01-01 221923](https://github.com/foxyproxy/browser-extension/assets/64642374/98f738f9-a820-4880-946e-162572481b6a)

**Comment by erosman** [comment]
The pattern set under `"title": "Pass through"` doesn't have any server associated with it.
FoxyProxy 8 requires a server to put the patterns under it.
For now, add a server to it e.g.
```
    "title": "Pass through",
    "active": true,
    "address": "DIRECT",
```

I have updated the import function to handle this case for v8.9.

**Comment by Nishantbhagat57** [comment]
That worked! Thanks :)
