### ISSUE TITLE
HTTPS/SSL type failure -- need option to not verify proxy's own cert

### ISSUE THREAD

**Issue by paulraines68** [foxyproxy/browser-extension#11]
I have an Apache server at work I have been using as a proxy with FoxyProxy via an ssh tunnel for years successfully on port 80 with the proxy type of HTTP.    I run from my laptop "ssh -L8080:proxy:80 sshgatewaybox" into my ssh gateway and this lets me access my internal only web services from outside the work firewall.  The Apache server "proxy" is configure with

```
<IfModule mod_proxy.c>
     ProxyRequests On
     AllowCONNECT 8443
     AllowCONNECT 443
     AllowCONNECT 8080
     <Proxy *>
         Order deny,allow
         Deny from all
         Allow from 127.0.0.1
         Allow from IP_of_ssh_gateway_box
     </Proxy>
</IfModule>

<VirtualHost _default_:443>
...
...
SSLProxyEngine on
SSLProxyVerify require
...
...
</VirtualHost>
```

and FoxyProxy is setup with proxy type HTTP, host localhost, port 8080 and patterns to match my internal servers.  This all has worked fine for years for both internal http and https sites.

But I decided to up my security game and get the communication to the proxy from the ssh gateway box to be over SSL too.  So I modified FoxyProxy to proxy TYPE HTTPS/SSL, host localhost, port 8080 and changed my ssh to "ssh -L8080:proxy:443 sshgatewaybox"

Now all attemps to use the proxy fail with Firefox security warning  SSL_ERROR_BAD_CERT_DOMAIN.  The detailed message is basically:

`Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for internalsite.domain. The certificate is only valid for the following names: proxy.domain
`
Basically now all sites appear to be using the proxy's certificate instead of their own certificate and Firefox throws the  SSL_ERROR_BAD_CERT_DOMAIN error.  I cannot even use the "Accept Risk and Continue" button as it just throws the same error again.

Even more weird is using the proxy to go to the proxy's own website fails saying:  

`Firefox does not trust this site because it uses a certificate that is not valid for proxy.domain. The certificate is only valid for the following names: proxy.domain`

Which makes no sense since the names are the same!

I will add I am running 'tcpdump host proxy and port 443' on the internalsite box and never see any traffic so things are not getting past the proxy at all.  And the Apache logs on the proxy show no useful messages about it.  So it appears the issue is Firefox/FoxyProxy is just refusing to use the proxy at all.  The proxy is using a fully valid certificate signed by a major CA

Is the issue that the FoxyProxy config has the host as localhost (since we are going over the ssh tunnel)?

Hmm.  I just edited \Windows\System32\drivers\etc\hosts on my laptop to add the line

`127.0.0.1 localhost proxy.domain`

and changed the FoxyProxy config from localhost to proxy.domain and now it works.  

So I guess this ticket is turning into a feature request in the proxy configuration where you can ask FoxyProxy to ignore (not verify) the certificate of the proxy itself when using type HTTPS/SSL

**Comment by erosman** [comment]
### Background

FoxyProxy (like any other extension) facilitates the use of certain functions of the browser, if the browser has provide an API for the extension to do so. These functions are set and controlled by the browser.

As mentioned in [Help](https://foxyproxy.github.io/browser-extension/src/content/help.html#proxy), Firefox & chrome, do not proxy `localhost, 127.0.0.1/8`, and `::1`. They also handle local servers differently, which might include obtaining certificates (_requires verification_).

The workaround that you have listed makes the local domain appear as a remote domain.

### Accept Risk and Continue

The SSL certificate issue in this case relates to the proxy and not the website, even though browser reports it as a bad website certificate. However, "Accept Risk and Continue" will be applied to the website domain and not the proxy, therefore the problem remains. 

In this situation, browser only deals with `proxy` SSL certificate and not the `website` SSL certificate. 

_Browser ⮕ proxy ⮕ website_

### Certificate Exception

A Certificate Exception for the proxy can only be added manually e.g.

- Firefox
  _Settings ⮕ Privacy & Security ⮕ Certificates ⮕ View certificates... ⮕ Certificate Manger ⮕ Servers ⮕ Add Exception..._ 

FoxyProxy (or any other extension) can not add such exceptions.

> So I guess this ticket is turning into a feature request in the proxy configuration where you can ask FoxyProxy to ignore (not verify) the certificate of the proxy itself when using type HTTPS/SSL

SSL certificates are handed by the browser and an extension has no power to intervene.

### View Certificate Issues

You can disable proxy use, open your local server in a browser tab (i.e. https://proxy.domain/) and inspect the issue. You can also view the certificates in Certificate Manger.

**Comment by paulraines68** [comment]
Okay, so disabling proxy cert verification is not something FoxyProxy can technically do.  It would require a change to Firefox architecture.  So one must use a workaround hack.  I will close this issue but maybe something about it can go in the FAQ.

Since the certificate for my proxy is a valid one, Firefox doesn't actually let me add it as an exception.  So that workaround does not work for me.

I will have to stick with the hosts file workaround I found.  The only issue there is confusion on my laptop when I am at work and actually try to go to that proxy host as a normal website it will fail (since it will try to connect my laptop itself).  Fortunately my proxy host certificate has an alternate name I can use as the proxy host name for this purpose that I would not ever try to go to as a normal website (or any other reason on the network) to avoid that confusion.
