### ISSUE TITLE
Proxy is falling back to dafault settings when proxy is unavailable instead of blocking the request

### ISSUE THREAD

**Issue by jeffrigby** [foxyproxy/browser-extension#110]
I have a proxy configuration that points to a local stunnel. In previous versions, if stunnel was not started, I would get an error. In the newest version, if stunnel is disabled the browser ignores it and sends the request with the default firefox settings, bypassing the proxy. This is a security risk for me. It's essential that when the proxy is enabled, no requests are sent outside of the proxy.

I have a standard wildcard to catch all URLs.

I see in the log that it tries the proxy and then falls back (see image)

As soon as I start stunnel, the requests are proxied correctly. Nothing has changed with my configuration, so I'm not sure when this started.
![proxySettings](https://github.com/foxyproxy/browser-extension/assets/9286474/cda481b7-1c26-4b90-b007-449611fa4be4)
![log](https://github.com/foxyproxy/browser-extension/assets/9286474/e40c88fc-58f5-46ac-a252-9ba681ba46ef)

**Comment by erosman** [comment]
FoxyProxy does not set a fallback process. FoxyProxy tells the browser (Firefox in this case) to process `abc` request via `xyz` proxy.
From then on, everything is handled by the browser.

FoxyProxy is not aware if the proxy server is responding or not.

FoxyProxy v7.5.1 had a similar process in [matcher.js](https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/matcher.js), so there shouldn't be a difference in behaviour between v7.5 & v8.8

**Comment by jeffrigby** [comment]
This has fixed itself. I didn't change anything directly, but it returned to denying the request if stunnel was down. Firefox updated, and I restarted. Unfortunately, I have no idea why it stopped working or started working again.
