### ISSUE TITLE
Proxy by pattern not working as it did before

### ISSUE THREAD

**Issue by inclementweather** [foxyproxy/browser-extension#111]
Hi, thank you for providing this plugin for free.  It has been a reliable workhorse for a number of years.  

Pattern matching doesn't seem to work the way it previously did what I have proxy by pattern enabled.  Either it tries to proxy when it shouldn't or it wouldn't proxy when it should.  My setup has 5 proxies configured and some have multiple patterns which are mixture of regex and wildcard.  I tried flipping specific patterns on/off under the proxy it was trying to use but it didn't have any affect.  I'm not sure if it was just using the first proxy in the list or what.  I couldn't figure out exactly what the issue was so I downgraded back to 7.5.1 and the proxy by pattern works again.  My settings also were lost when I upgraded, not sure if that's related but I was able to export my settings from another computer and import them in the new version.  Although it did complain about some of my regex patterns which I fixed.

I can't really upload my config, it has a lot of details about my network.  Just wanted to provide some feedback.  Sorry if this isn't useful.

**Comment by erosman** [comment]
The issue with the migration of the settings should have been sorted out. Were you testing the latest version of FoxyProxy?

Please note that in FoxyProxy 8, the patterns can match the entire URL, while in FoxyProxy 7 it only matched the host.

If you post some patterns that you think are not working, we can try to find out the problem.
