### ISSUE TITLE
Change icon to proxy name/color used for tab url

### ISSUE THREAD

**Issue by NewtonChutney** [foxyproxy/browser-extension#114]
If I'm not wrong, the version before the Chrome codebase and Firefox were merged, did update the icon color/name to reflect the proxy used for the page's URL
It appears that is no longer the case.. Also, there's no indicator for the `Set Tab proxy` function. This could help it

Firefox v121.0
FoxyProxy v8.8 (22 Dec, 2023)

Edit: I check for duplicates but couldn't find any, please do close this in that case

**Comment by erosman** [comment]
> If I'm not wrong, the version before the Chrome codebase and Firefox were merged, did update the icon color/name to reflect the proxy used for the page's URL

FoxyProxy v3-8 changed the icon badge to show the proxy when a single proxy is selected (for all).
That hasn't changed.

FoxyProxy v7, changed the icon badge when in "Proxy by Patterns" mode as well _(Firefox only, not possible on Chrome)_. However, that was NOT per tab and the same proxy was shown for all the tabs.

FoxyProxy 8, initially dropped the feature but on demand (#57), re-added the feature in v8.7 behind a "Show Pattern Proxy" options.
Additionally, the new feature is per-tab, so the proxy is specific to each tab.

> Also, there's no indicator for the Set Tab proxy function. 

There is an indicator which is the FoxyProxy icon shown inside the address-bar. On mouse-over, it also shows the details of the proxy involved.

**Comment by NewtonChutney** [comment]
> FoxyProxy v7, changed the icon badge when in "Proxy by Patterns" mode as well _(Firefox only, not possible on Chrome)_. However, that was NOT per tab and the same proxy was shown for all the tabs.

Ahh, that makes so much sense... Now I understand the random glitches when other tabs load.. 
Thanks for the fix that made it per-tab

> There is an indicator which is the FoxyProxy icon shown inside the address-bar. On mouse-over, it also shows the details of the proxy involved.


Ahh... this indicator.. 
![Untitled](https://github.com/foxyproxy/browser-extension/assets/70827815/a5f1b1de-bd62-4eb1-b986-fff0f4a4e556)
but in case we select show proxy per tab, this creates confusion to the user.. I'd say we override that indicator too?

**Comment by erosman** [comment]
There are some changes in v8.9.

- Removed "Show Pattern Proxy" option and made it default (from 8.7) (Firefox only)
- Removed Tab Proxy page-action and set it to the toolbar icon (Firefox only)
