### ISSUE TITLE
PAC file proxy isn't available in Set Tab Proxy

### ISSUE THREAD

**Issue by belperite** [foxyproxy/browser-extension#115]
Hello again and thank you for this very useful addon.

I want to set a tab proxy which uses a PAC file, however this isn't available in the dropdown list (the "BDE" one in this case). Is this a bug, or a limitation perhaps?

Firefox, macos.

Thanks,
Richard

<img width="295" alt="Screenshot 2024-01-09 at 13 53 05" src="https://github.com/foxyproxy/browser-extension/assets/33836503/b3232192-e88b-4390-a31f-1ffe098218f8">

**Comment by erosman** [comment]
PAC (Proxy Auto-Configuration file) is set via Firefox's Network Settings.
Once PAC is set, all proxying controls are passed to the Firefox & the PAC.

That is the reason PACs are filtered out in the popup, since it is not possible to set them for a tab.

**Comment by belperite** [comment]
Fair enough! Thanks for responding.
