### ISSUE TITLE
"Quick Add" button gives no response

### ISSUE THREAD

**Issue by sh3ll4rpw** [foxyproxy/browser-extension#117]
Quick add button in the toolbar menu gives no response

**Comment by erosman** [comment]
What response do you expect?
Have you checked the proxies to see if the pattern was added?

**Comment by sh3ll4rpw** [comment]
Adding a new proxy profile? That's for me the most interpretation. I click on it and nothing happens

**Comment by erosman** [comment]
From [FoxyProxy Help](https://foxyproxy.github.io/browser-extension/src/content/help.html)

> **Quick Add**
> - Add current page's host pattern to the selected proxy's include
> - Only top 10 active proxies are listed

- Have you selected a proxy to add the host patter to?
- Did it add it?

**Comment by Bl0ckbuster** [comment]
> From [FoxyProxy Help](https://foxyproxy.github.io/browser-extension/src/content/help.html)
> 
> > **Quick Add**
> > 
> > * Add current page's host pattern to the selected proxy's include
> > * Only top 10 active proxies are listed
> 
> * Have you selected a proxy to add the host patter to?
> * Did it add it?

Wow. This is one that I should have read the manual a little closer for. I've been trying the same thing under the same impression for months now, and skimmed that part apparently.  Thanks for posting that. It just saved me a bunch more time researching something that I didn't need to (if I read the manual properly)! :)

**Comment by erosman** [comment]
FYI... The UI is updated in v8.10 which should make it easier for the users.

**Comment by Bl0ckbuster** [comment]
Awesome news! That's the next version?

**Comment by erosman** [comment]
> Awesome news! That's the next version?

Yes ...

**Comment by shamefulCake1** [comment]
This button is not there any more?

**Comment by erosman** [comment]
@shamefulCake1 As per Changelog:

### 9.0

- Renamed "Quick Add" to "Include Host"
- Repurposed "Exclude Host" to match "Include Host" function
