### ISSUE TITLE
Can't change between socks5 profiles that have the same IP and port

### ISSUE THREAD

**Issue by sh3ll4rpw** [foxyproxy/browser-extension#118]
I connect to my socks5 through a server. So I add socks in foxyproxy that have the same IP and port, but different auth credentials. Many socks suppliers work like this nowadays. 

When I add multiple socks with all the same IP and port. I can't change between these profiles. It always automatically select the profile which is the highest in list/order. Even when I've that profile disabled. When I delete that profile, it is still selected. And when I restart firefox the deleted profile is back. Probably because there is another profile that has the same IP and port

**Comment by sh3ll4rpw** [comment]
Added additional issues to the initial bug report

**Comment by erosman** [comment]
Previously: #76
