### ISSUE TITLE
On startup Firefox connects directly, ignoring Foxyproxy rules

### ISSUE THREAD

**Issue by gittyhub888** [foxyproxy/browser-extension#12]
Firefox 108.0.2, Foxyproxy 7.5.1

Hi,
I have a few tabs open and when I close and reopen Firefox (I set the option to restore the tabs from the previous session) then Firefox connects directly to the web sites in the tabs, completely ignoring the rules set in Foxyproxy.
Btw, these connections do not show in the Foxyproxy log.

Is that a bug or expected?

Thanks for your help.

**Comment by ericjung** [comment]
This is a known Firefox bug, not FoxyProxy. The FoxyProxy extension is not fully loaded before Firefox starts making network requests.

**Comment by erosman** [comment]
Previously:

- [Site not being proxied at startup](https://github.com/foxyproxy/firefox-extension/issues/179)
- [For a brief moment when starting the browser foxy proxy is not working](https://github.com/foxyproxy/firefox-extension/issues/143)
