### ISSUE TITLE
Incorrect import of a proxy with `socks` protocol

### ISSUE THREAD

**Issue by lessneek** [foxyproxy/browser-extension#120]
On `Import Proxy List` a proxy with `socks://` protocol is imported with empty hostname and port.

Versions:
```
Firefox 121.0.1
FoxyProxy 8.8
```

**Comment by erosman** [comment]
Can you give an example?

I tried with these and there were no problems.
```
socks://100.10.11.12:1080?title=China&cc=CN&city=Beijing
socks5://100.10.11.12:1080?title=China&cc=CN&city=Beijing
```

**Comment by lessneek** [comment]
I've tried these and what I've got:
![image](https://github.com/foxyproxy/browser-extension/assets/289916/89c63009-bf8e-4be3-b867-c003da591dc9)

**Comment by erosman** [comment]
Which version of FoxyProxy are you using and which browser?

**Comment by lessneek** [comment]
> Which version of FoxyProxy are you using and which browser?

Firefox 121.0.1
FoxyProxy 8.8

**Comment by erosman** [comment]
I tested it now with v8.8 on Firefox Nightly and I don't get any problems.

Please try the following:

- Export your settings (to have a back-up)
- Uninstall FoxyProxy (better to restart Firefox after to clear its cache)
- Reinstall FoxyProxy
- Test again

**Comment by lessneek** [comment]
I have tries with an empty Firefox this in console, and it seems that a URL with the `socks` protocol is not parsed correctly. I can replace `socks` with `asdf` and the result will be the same:
![image](https://github.com/foxyproxy/browser-extension/assets/289916/bcc85cea-6353-4ebb-aafc-4fdabfd1fb1a)

**Comment by lessneek** [comment]
May be we can replace the `URL` parsing method with a simple regular expression?

**Comment by erosman** [comment]
> I have tries with an empty Firefox this in console, and it seems that a URL with the `socks` protocol is not parsed correctly.

That is why FoxyProxy code reprocesses it. I don't get any error when I try it.

- The code checks if protocol is `http:` or `https:`
- if not:
  - Sets the type according to the protocol
  - Changes the protocol to `http:`
  - Runs `new URL(url)` again with `http:`

https://github.com/foxyproxy/browser-extension/blob/172c936be1f6ffa4450f5e5186c48794aa8037ba/src/content/options.js#L1019-L1041

**Comment by lessneek** [comment]
> Sets the type according to the protocol

when I debug, protocol isn't changed after assignment:

```js
url = new URL("socks://10.10.1.2:1080")
< URL { href: "socks://10.10.1.2:1080", origin: "null", protocol: "socks:", username: "", password: "", host: "", hostname: "", port: "", pathname: "//10.10.1.2:1080", search: "" }

url.protocol = "http"
< "http"

url
< URL { href: "socks://10.10.1.2:1080", origin: "null", protocol: "socks:", username: "", password: "", host: "", hostname: "", port: "", pathname: "//10.10.1.2:1080", search: "" }
```

**Comment by erosman** [comment]
Strangely enough, when I test with FoxyProxy 8.8, it works for me without any errors.

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/79608178-1f90-489b-a4c4-607760873231)

**Comment by erosman** [comment]
It seems `new URL()` was updated in Firefox 122 ([Bug 1603699: Enable DefaultURI use for unknown schemes](https://bugzilla.mozilla.org/show_bug.cgi?id=1603699)).

**Comment by erosman** [comment]
v8.9 uploaded to AMO
Basic version is aviallable now and standard version will be available after the AMO review.

**Comment by erosman** [comment]
v8.9 uploaded to AMO
Basic version is available now and the standard version will be available after the AMO review.
