### ISSUE TITLE
FoxyProxy is incompatible with the SpoofDPI proxy server

### ISSUE THREAD

**Issue by vukitoso** [foxyproxy/browser-extension#121]
Hi.

FreeBSD 13.2
Firefox 121.0.1
FoxyProxy 8.8

Installed the SpoofDPI server on the local HTTPS machine - https://github.com/xvzc/SpoofDPI
Launched SpoofDPI as 127.0.0.1:8080

When you add HTTPS proxy 127.0.0.1:8080 from SpoofDPI to FoxyProxy, the connection is not established, in the SpoofDPI logs there is gibberish.
If you add proxy 127.0.0.1:8080 to the Firefox system settings (without FoxyProxy), then connections are established, everything is fine.
Everything works fine via curl too:
`curl -v -I -X GET --proxy 127.0.0.1:8080 https://facebook.com`

I assume that the problem is somewhere in FoxyProxy.
Thx.

**Comment by erosman** [comment]
> When you add HTTPS proxy 127.0.0.1:8080 from SpoofDPI to FoxyProxy,

`127.0.0.1:8080` should be HTTP proxy (not HTTPS).
Try setting the "Type" to HTTP and check again.

**Comment by erosman** [comment]
> I didn’t know that the HTTP proxy supports the HTTP CONNECT method and through which HTTPS can work successfully.
I thought HTTP was pure HTTP, without HTTPS.

That was how proxies behaved in the early days. Sadly, Firefox's build-in proxy option still works that way ([Bug 1804693: Setting single proxy for all fails](https://bugzilla.mozilla.org/show_bug.cgi?id=1804693)).
That means HTTP proxy for HTTP target and HTTPS proxy for HTTPS target.
That was designed when HTTPS was new and very few sites used it.

Modern proxy servers forward requests and the proxy server's own protocol is not relevant to the forwarding. The final SSL communication and decryption still happen between browser & the target site.
