### ISSUE TITLE
The tab bar is stuck on progress bar

### ISSUE THREAD

**Issue by DarthGandalf** [foxyproxy/browser-extension#122]
Version 3.9.21, firefox 121.0 on gentoo linux

![Выделение_512](https://github.com/foxyproxy/browser-extension/assets/325092/491c0291-bea2-48e7-b411-71371d10aff9)

The only relevant message from Browser Console looks like this:

Key ext-key-id-treestyletab_piro_sakura_ne_jp-sidebar-action of menuitem Tree Style Tab could not be found menu.js:293:21 (chrome://global/content/elements/menu.js)

**Comment by erosman** [comment]
> Version 3.9.21, firefox 121.0 on gentoo linux

Is that FoxyProxy version 3.9.21?

> Key ext-key-id-treestyletab_piro_sakura_ne_jp-sidebar-action of menuitem Tree Style Tab could not be found menu.js:293:21 (chrome://global/content/elements/menu.js)

That doesn't relate to FoxyProxy.

**Comment by DarthGandalf** [comment]
Sorry :(
Wrong extension
