### ISSUE TITLE
didn't forward all traffic

### ISSUE THREAD

**Issue by maanimis** [foxyproxy/browser-extension#123]
thanks for your useful project
but it can't forward all traffic. i didn't have problem in older versions
log:
![image](https://github.com/foxyproxy/browser-extension/assets/106465992/bb9db418-82a4-45a9-bc80-3b517dcb23c0)

my proxy&patterns:
![image](https://github.com/foxyproxy/browser-extension/assets/106465992/0af10f29-21ef-4f97-a616-2b2f0a3345de)

**Comment by erosman** [comment]
- What is FoxyProxy version and the browser?
- Is that the only proxy you are using?
- Are there other proxies with patterns?

> i didn't have problem in older versions

In FoxyProxy v7, patterns only matched the host, but in v8+ it can match the entire URL (like it used to be in v3). That can cause unexpected matches. 

Although not an issue, I would suggest simplifying the pattern usage.

- It seems `.ir, aparat.com, bargheman.com, cloudfare.com, google.com, igap.net` are permanent exclusions. In that case, they would be better placed under Global exclude (which only matches the host)
- In v8, those long regex (4th, 5th, & 6th) patterns should not be needed anymore
- If you are only using a single proxy, and it has a match all pattern, it would be easier and more efficient to:
  - Add the excludes to the Global Exclude (as mentioned above)
  - Use the server for all (without any patterns)
