### ISSUE TITLE
socks5 proxy (ssh -D) Firefox MAC not working anymore

### ISSUE THREAD

**Issue by mhbacks** [foxyproxy/browser-extension#125]
Hi,
around a month the socks5 proxy is not working anymore with foxyproxy standard and basic.
When i disable foxyproxy and use the firefox settings it is working

Firefox 122.0.1 (64-Bit)
Foxyproxy Version 8.9

# Reproduce the issue

on Mac:
ssh -D8888 user@remotehost
start firefox
in connection settings set socks5 proxy 127.0.0.1 port 8888 no authentication
open a website. 
it is working

in connection settints set "no proxy"
in foxyproxy create new proxy "localhost" with socks5 127.0.0.1 port 8.8.8.8
save
in foxyproxy choose proxy "localhost"
try to open previously tested website
issue: proxyserver reset connection

edit:
i tried also version 8.8, same behaviour.

**Comment by erosman** [comment]
> in foxyproxy create new proxy "localhost" with socks5 127.0.0.1 port 8.8.8.8

Is that `8.8.8.8`?

**Comment by mhbacks** [comment]
> > in foxyproxy create new proxy "localhost" with socks5 127.0.0.1 port 8.8.8.8
> 
> Is that `8.8.8.8`?

Oha! sorry, i mean 8888 ;-)

**Comment by mika-cn** [comment]
@mhbacks

What did you mean "proxyserver reset connection" ?  Was this the message that display by Firefox?

**Comment by mhbacks** [comment]
Hi,
at first, sorry for the late response. 
I think I need a vacation. I've been using the Socks5 proxy for years and wondered why it wasn't working. Unfortunately, after reading your comments and thinking about it, I realized that I put the same crap in the proxy field :facepalm:

I'm old. Thanks for helping me across the street.
best regards,
Max
