### ISSUE TITLE
Proxy by patterns does not work for https://www.tiktok.com/favicon.ico

### ISSUE THREAD

**Issue by songliansheng** [foxyproxy/browser-extension#126]
I define two proxy: Bypass and ProxyAll (I attached the screenshot below), [tiktok.com](url)、[google.com](url) are not in the bypass list ,when proxy by patterns , The log is as shown in my screenshot.

tiktok.com is proxied ，but https://www.tiktok.com/favicon.ico bypass the proxy

[google.com](url) can be opened ,but when google search "favicon.ico" or "any keyword +favicon.ico" , the request bypass the proxy

Maybe other websites  also have this problem(about favicon.ico)

![Screenshot 2024-02-28 222251](https://github.com/foxyproxy/browser-extension/assets/17312817/fa06ed02-7308-4af2-8e9b-98bd954758c1)

![Screenshot 2024-02-28 222806](https://github.com/foxyproxy/browser-extension/assets/17312817/52dc68cd-e262-4e86-8c27-7eac828ecd08)

![Screenshot 2024-02-28 224701](https://github.com/foxyproxy/browser-extension/assets/17312817/15b728c9-a2b8-42dd-8d2f-f336ed00d92f)

**Comment by erosman** [comment]
What are the patterns in your Bypass?

_PS. #123 might also be useful to you._

**Comment by songliansheng** [comment]
> What are the patterns in your Bypass?
> 
> _PS. #123 might also be useful to you._

Thank you so much , you reminded me，the problem is with my bypass list ，but I can't figure out why and when I added this item

![Screenshot 2024-02-29 081714](https://github.com/foxyproxy/browser-extension/assets/17312817/9b6dccb6-9785-4d07-a7d2-0a82da92b4ff)
