### ISSUE TITLE
[Question] Restoring all foxyproxy settings after reinstall - Firefox

### ISSUE THREAD

**Issue by Crrispy** [foxyproxy/browser-extension#128]
Hello,

I just did a full reinstall of my PC, starting from Windows. I always backup the Firefox profile folder before doing this, and restore it after reinstallation, so I find everything back in Firefox exactly where i left. But foxyproxy settings seem to be stored elsewhere since it is now empty :-(

How can I reimport all settings (socks, patterns, etc..)? I have a full backup of the C disk before reinstall.

Thanks.

**Comment by erosman** [comment]
Extension storage is handled by Firefox.
It is in a IDB in the following folder under `moz-extension+++[UUID]`

```
C:\Users\[user]\AppData\Roaming\Mozilla\Firefox\Profiles\[profile]\storage\default
```

You can get the folder by going to `about:profiles`
