### ISSUE TITLE
Proxy patterns ignored on tabs

### ISSUE THREAD

**Issue by ncMaothVez** [foxyproxy/browser-extension#130]
Not entirely sure if this is a bug or by design.  
I would like to to be able to use patterns when enabling a proxy config on individual tabs.

FoxyProxy 8.9 on FireFox

I've got a single proxy config like this:
![fp_config_001](https://github.com/foxyproxy/browser-extension/assets/164012115/09f03781-72b8-4cf7-b9a2-d2e82a097454)

If I enable Proxy By Patterns like this then everything works as expected; only requests to Google are routed through the proxy:
![fp_config_002](https://github.com/foxyproxy/browser-extension/assets/164012115/5d50a21b-6a5d-489e-b85d-eef25c4081bf)

If I disable Proxy By Patterns and instead select the proxy config and click "Set Tab Proxy" like this then the config does is activated only on that tab (as expected) but the config's patterns are ignored and all requests to all domains, not just Google, from the tab are routed through the proxy:
![fp_config_003](https://github.com/foxyproxy/browser-extension/assets/164012115/48cadf46-25a5-4548-ab43-f1d0d2a2cd4d)

**Comment by erosman** [comment]
When a single proxy is set for all, patterns are ignored and everything passes through that proxy.

Tab Proxy is the same as single proxy but for a single tab. Therefore, everything passes through that proxy.

The only options that takes pattern into consideration is "Proxy by Patterns".

**Comment by ncMaothVez** [comment]
Thanks for the quick reply! OK, makes sense.
