### ISSUE TITLE
SOCKS5 proxy NordVPN authentication 

### ISSUE THREAD

**Issue by katastrophe92** [foxyproxy/browser-extension#15]
Hello. It is possible to add a socks5 proxy with my NordVPN authentication? Thanks
![24 01 2023  15-23-23](https://user-images.githubusercontent.com/103950507/214319787-7ba31dae-2c24-41ed-b592-70b845639227.png)

**Comment by mjpieters** [comment]
Yes, just fill in the information for any of those proxies into the proxy screen:

<img width="1161" alt="image" src="https://github.com/foxyproxy/browser-extension/assets/46775/00c85f60-87d5-4631-898c-140a9968530d">
