### ISSUE TITLE
Wrong proxy is enabled when two proxies with same ip:port

### ISSUE THREAD

**Issue by t1m013y** [foxyproxy/browser-extension#150]
I have two proxies with same ip and port:
![Screenshot 2024-08-23 at 11-28-44 FoxyProxy Настройки](https://github.com/user-attachments/assets/23525cf7-cbd8-4746-89a6-fc87214383b1)
When I enable SOCKS5 proxy for single tab, SOCKS4 is actually enabled:
![screenshot_2024-08-23](https://github.com/user-attachments/assets/974f6058-dde2-4c24-beff-8d5e11cbb1ad)
![screenshot_2024-08-23 (1)](https://github.com/user-attachments/assets/eb702a09-99db-4675-b446-d4da9f11428c)
![screenshot_2024-08-23 (2)](https://github.com/user-attachments/assets/44748df8-e58b-470b-a1bc-a2a612bf1149)

**Comment by erosman** [comment]
Previously #143 

Please read https://github.com/foxyproxy/browser-extension/issues/143#issuecomment-2243543288
