### ISSUE TITLE
Choosing only a few websites to get proxied

### ISSUE THREAD

**Issue by KirbyFan102** [foxyproxy/browser-extension#153]
What the title says. The Global Exclude option is not ideal for this purpose, and I don't know where to find such a thing in the options.

Also, I don't why but I can't seem to enable FoxyProxy at all when I click the button. Please help, I'm new at this.

**Comment by erosman** [comment]
FoxyProxy  has 2 types of proxying:

- All via a single server/proxy
- "Proxy by Patterns" (choose which URLS to proxy)

If you want to choose which websites to proxy, then you need to use "Proxy by Patterns" and assign those websites under the desired proxy.

Please note that many websites use multiple domains within a page and users may have to include all those domain for the website to function properly.

See also: Included Help under "Pattern Guide"

**Comment by KirbyFan102** [comment]
Okay, does this work?
![image](https://github.com/user-attachments/assets/d7705c15-93de-413f-b127-763788afbb84)

**Comment by erosman** [comment]
It looks fine, although you don't need number 1 & 3 as number 2 & 4 do the same job.

If you want to catch both `twitter.com` and its subdomains, it would be safer to have:

```
://twitter.com/
://*.twitter.com/
```

`://*twitter.com/` can match `https://abc.sometwitter.com/` which I  guess you dont want to match.

**Comment by KirbyFan102** [comment]
Thank you for the feedback sir, I will make sure to follow your advice 🙏

Unfortunately, I tried it out (using Proxy by Patterns) and have not been able to get the website to load. I think it may be a problem with the proxy server I'm using, but I'm not sure how I would go about checking that. I got it from a free server list.

Weirdly, website works fine when I use a VPN, but I would still prefer to use a proxy.

**Comment by erosman** [comment]
>  I think it may be a problem with the proxy server I'm using, but I'm not sure how I would go about checking that.

Test by using that proxy for ALL (select it from the toolbar popup).

- if the page doesn't load, then it is an issue with the proxy
- if the page loads fine, then there is an issue with patterns (it has domains that need to be added to the patterns)

**Comment by KirbyFan102** [comment]
Yeah, it doesn't load if I select the proxy from the popup. Actually, no websites work with it. Darn. I guess I'll have to keep trying them until one works.

Anyways, thanks again for helping me troubleshoot. I'll mark this issue as solved for now.
