### ISSUE TITLE
FoxyProxy 8.9 - DNS leak in Firefox 130.

### ISSUE THREAD

**Issue by Alexey104** [foxyproxy/browser-extension#154]
I use Foxyproxy with Shadowsocks running on a remote server to selectively proxy requests to some websites matching the regex rules. `Proxy DNS` is `ON`. `Uncloak canonical names` is unchecked in UblockOrigin settings. Everything had been working fine until recently I noticed that my ISP DNS is used alongside with the proxy DNS, and this is the problem for me because my ISP blocks DNS queries to some sites redirecting me to a stub page. The issue is reproducible with all other addons being disabled. If I set the same SOCKS5 proxy in Firefox proxy settings with `Proxy DNS when using SOCKS v5` checked, there is no DNS leak, it only happens when using Foxyproxy, and it started to happen recently. Previously there were no DNS leaks.  Not sure, maybe this is related to upgrading to Firefox 130.

**Comment by Alexey104** [comment]
OK, just out of curiosity I tried another proxy extension and it also leaks DNS with the `proxy DNS` option `ON`, so the problem seems to be related to Firefox API, not to Foxyproxy itself. Not sure, should I close this?

**Comment by Alexey104** [comment]
Just for the info:

By downgrading Firefox I've found out that the issues appeared in 129 and above. No problems with 128. Will try to report on bugzilla.

**Comment by erosman** [comment]
Please note https://github.com/foxyproxy/browser-extension/issues/142#issuecomment-2233819048

**Comment by Alexey104** [comment]
OK, thank you, [I reported this at bugzilla.](https://bugzilla.mozilla.org/show_bug.cgi?id=1920399)

**Comment by Francewhoa** [comment]
Related challenge at https://github.com/foxyproxy/browser-extension/issues/166
