### ISSUE TITLE
Regexp exclude filter does not work

### ISSUE THREAD

**Issue by notDavid** [foxyproxy/browser-extension#158]
Hi there,

the exclude filter does not work as i would expect.
Either i misunderstand how it works, or there's a bug. Please see the attached screenshots and advise...

- first filter was added via "quick add" in the toolbar
- second filter is the Foxyproxy-built-in filter in the "Quick Add" dropdown list

- version 8.9
- Firefox 131.0 (aarch64), macOS

Thank you!

<details>
  <summary>1_proxy_filter_exclude</summary>

![1_proxy_filter_exclude](https://github.com/user-attachments/assets/0569a473-bf09-4d55-935f-b5492ed5b689)

</details>

<details>
  <summary>2_log</summary>

![2_log](https://github.com/user-attachments/assets/fcff76b8-2bda-4190-a0c8-a2758e645e66)

</details>

<details>
  <summary>3_pattern_test_1</summary>

![3_pattern_test](https://github.com/user-attachments/assets/f4a5a04d-a38a-4fd9-a145-b5e90683cc0d)

</details>

<details>
  <summary>4_pattern_test</summary>

![4_pattern_test](https://github.com/user-attachments/assets/fee91d60-22ab-4499-a971-d0710349f3f4)

</details>

**Comment by erosman** [comment]
Is FoxyProxy set to "Proxy by Patterns"?

**Comment by erosman** [comment]
The Options page is were users set the configurations.
The toolbar icon popup is where users set the mode of the FoxyProxy i.e. Proxy by Patterns, Disable, or individual proxy.

In order for "Proxy by Patterns" to work (and show in the popup) there must be at least one proxy with an include pattern to know where to apply the proxy.

Patterns (include/exclude) are only applied in "Proxy by Patterns".
Selecting an individual proxy server in the popup would mean EVERYTHING will go through that server.

**Comment by erosman** [comment]
There is a Help included in the addon explaining all the features.

> My goal is simply to exclude all RFC1918 (local) networks and 127.*

For that purpose, it would be better and more efficient to use Global Exclude.
