### ISSUE TITLE
Is there any way to create proxies outside of the GUI?

### ISSUE THREAD

**Issue by Sechorda** [foxyproxy/browser-extension#159]
Are there any editable config files outside of the GUI to create a proxy?

Thank you!

**Comment by erosman** [comment]
Few options:

- Export the current preferences and then edit the JSON, (e.g. add/remove proxies) and then import the preferences
- Use _Import -> Import Proxy List_

**Comment by erosman** [comment]
> Can I edit the JSON directly somewhere?

You can use any text editor

> Can I import via CLI or via script?

There is no direct CLI support to extensions.

You can use [Enterprise Policy](https://foxyproxy.github.io/browser-extension/src/content/help.html#enterprise-policy) (or managed storage) and those can be edited via CLI or script.

**Comment by Sechorda** [comment]
> > Can I edit the JSON directly somewhere?
> 
> You can use any text editor
> 
> > Can I import via CLI or via script?
> 
> There is no direct CLI support to extensions.
> 
> You can use [Enterprise Policy](https://foxyproxy.github.io/browser-extension/src/content/help.html#enterprise-policy) (or managed storage) and those can be edited via CLI or script.

LIFE SAVER

**Comment by Sechorda** [comment]
I am attempting to apply the policy but am not getting the desired proxy in the menu

what am I doing wrong?

```
"3rdparty": {
      "Extensions": {
        "foxyproxy@eric.h.jung": {
          "mode": "enable",
          "data": [
            {
              "title": "Caido",
              "type": 1,
              "color": "#66cc66",
              "address": "127.0.0.1",
              "port": 8080,
              "active": true
```

**Comment by erosman** [comment]
> "mode": "enable",

There is no such mode. An example of the mode would be:

```
"mode": "127.0.0.1:8080",
```

- Make a set up in FoxyProxy
- Export the preferences
- Examine the JSON
- Enterprise policy uses a similar format

Please note that if you use an Enterprise Policy, you wont be able to change anything from the FoxyProxy UI anymore. Everything will be set from the Enterprise Policy.

**Comment by Sechorda** [comment]
> > "mode": "enable",
> 
> There is no such mode. An example of the mode would be:
> 
> ```
> "mode": "127.0.0.1:8080",
> ```
> 
> * Make a set up in FoxyProxy
> * Export the preferences
> * Examine the JSON
> * Enterprise policy uses a similar format
> 
> Please note that if you use an Enterprise Policy, you wont be able to change anything from the FoxyProxy UI anymore. Everything will be set from the Enterprise Policy.

this didn't work for me

```
"3rdparty": {
      "Extensions": {
        "foxyproxy@eric.h.jung": {
          "mode": "127.0.0.1:8080",
          "data": [
            {
              "title": "Caido",
              "color": "#66cc66",
              "active": true
```

**Comment by erosman** [comment]
> this didn't work for me

There can be many reasons e.g. error in the the JSON, location, etc
Are you using Chrome or Firefox?
Does the policy show in the browser policies?
The JSON in your post is incomplete.

The included Help should have all the necessary information to set it up.

**Comment by erosman** [comment]
> how do I enable 'mode:'?

By setting the correct value which can be "pattern", proxy/port, or URL.
See https://github.com/foxyproxy/browser-extension/issues/159#issuecomment-2417992125

See also: #95, #138

**Comment by Sechorda** [comment]
> > how do I enable 'mode:'?
> 
> By setting the correct value which can be "pattern", proxy/port, or URL. See [#159 (comment)](https://github.com/foxyproxy/browser-extension/issues/159#issuecomment-2417992125)
> 
> See also: #95, #138

Ok, What would be the easiest way to get the proxy listed in foxyproxys?
I am building a OS by script/debootstrap and just need to have a correct policy or strategy to have this proxy configured

Thank you

**Comment by erosman** [comment]
The FoxyProxy enterprise policy resembles the FoxyProxy preferences export.

"mode" is the same.
"data" is the same.

Here is an example:

```json
{
  "policies": {
    "3rdparty": {
      "Extensions": {
        "foxyproxy@eric.h.jung": {
          "mode": "127.0.0.1:8080",
          "data": [
            {
              "active": true,
              "title": "Caido",
              "type": "http",
              "hostname": "127.0.0.1",
              "port": "8080",
              "username": "",
              "password": "",
              "cc": "",
              "city": "",
              "color": "#ff4500",
              "pac": "",
              "pacString": "",
              "proxyDNS": true,
              "include": [],
              "exclude": []
            }
        ]
        }
      }
    }
  }
}
```

**Comment by Sechorda** [comment]
> The FoxyProxy enterprise policy resembles the FoxyProxy preferences export.
> 
> "mode" is the same. "data" is the same.
> 
> Here is an example:
> 
> ```json
> {
>   "policies": {
>     "3rdparty": {
>       "Extensions": {
>         "foxyproxy@eric.h.jung": {
>           "mode": "127.0.0.1:8080",
>           "data": [
>             {
>               "active": true,
>               "title": "Caido",
>               "type": "http",
>               "hostname": "127.0.0.1",
>               "port": "8080",
>               "username": "",
>               "password": "",
>               "cc": "",
>               "city": "",
>               "color": "#ff4500",
>               "pac": "",
>               "pacString": "",
>               "proxyDNS": true,
>               "include": [],
>               "exclude": []
>             }
>           ]
>         }
>       }
>     }
>   }
> }
> ```

Thanks for this snippet!

If I set `active: false` does this mean it will be disabled and I can select it and disable it at-will, or is it always on?

**Comment by erosman** [comment]
> If I set `active: false` does this mean it will be disabled and I can select it and disable it at-will, or is it always on?

If "mode" is set to an inactive proxy, the FoxyProxy will be set to disable.
It is better to change to mode to disable FoxyProxy.

"active" is used when user has many proxies and wants to disabled some to keep the UI less overcrowded.
Another use for "active" is when user wants to disable associated patterns for "Proxy by Patterns".

**Comment by Sechorda** [comment]
> > If I set `active: false` does this mean it will be disabled and I can select it and disable it at-will, or is it always on?
> 
> If "mode" is set to an inactive proxy, the FoxyProxy will be set to disable. It is better to change to mode to disable FoxyProxy.
> 
> "active" is used when user has many proxies and wants to disabled some to keep the UI less overcrowded. Another use for "active" is when user wants to disable associated patterns for "Proxy by Patterns".

What options should I use is I want to be able to disable proxy, and select the one I set by policy?

**Comment by erosman** [comment]
If you are using CLI (or anything other than the UI), there is no need to change the "active" state of a proxy.
You can add as many proxies as you need.
You only need to change the "mode" e.g. switch between:

- 'disable" which means no proxy
- "host:port" of the selected proxy

**Comment by Sechorda** [comment]
> If you are using CLI (or anything other than the UI), there is no need to change the "active" state of a proxy. You can add as many proxies as you need. You only need to change the "mode" e.g. switch between:
> 
> * 'disable" which means no proxy
> * "hostname:port" of the selected proxy

which option allows me start with a proxy in the settings, and the proxy disabled. I can select it when needed, but it is off by default?

**Comment by erosman** [comment]
> which option allows me start with a proxy in the settings, and the proxy disabled. I can select it when needed, but it is off by default?

As I have already mentioned, "mode".
"mode" controls the proxying.

**Comment by Sechorda** [comment]
> > which option allows me start with a proxy in the settings, and the proxy disabled. I can select it when needed, but it is off by default?
> 
> As I have already mentioned, "mode". "mode" controls the proxying.

We have to agree that the example provided and the incomplete sentence that documents each Key:value pair is not intuitive to even a seasoned techie. 

You mentioned `"mode":` should be `127.0.0.1:8080`. does this mean the proxy is always on?
If I switch `"mode": to `disable`, where do I specify the proxy that I want available?

I hope my objective is clear, to have a proxy available to be chosen, but disabled by default. Can you please help me by providing an example snippet with this configuration?

Thank you

**Comment by erosman** [comment]
> You mentioned `"mode":` should be `127.0.0.1:8080`. does this mean the proxy is always on?

Yes... that is the purpose of Enterprise Policy. It controls the extension and it is fixed.
Enterprise Policy is read by the extension on browser start up and it is not possible to change it.

Please read more on the function of the Enterprise Policy. Enterprise Polices are advanced features meant for administrators.

> [storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/storage)
> Managed data declares the enterprise policies supported by the app. Policies are analogous to options but are configured by a system administrator instead of the user, enabling the app to be configured for all users of an organization.

> If I switch `"mode":` to `disable`, where do I specify the proxy that I want available?

All `"active"` proxies are available to the extension but only the one set in the "mode" is used (unless "Proxy by Patterns) is used). You can have 100s of them listed in the `"data"`.
Proxies can not be used when `"mode"` is set to `disable`. In this case FoxyProxy is disabled which mean no proxying at all.

**Comment by Sechorda** [comment]
> All `"active"` proxies are available to the extension but only the one set in the "mode" is used (unless "Proxy by Patterns) is used). 

Why would you be able to list more than one proxy if only one can be used and is always on by default? How can I achieve my goal of setting one proxy, not on by default - but able to be selected.

Essentially I would like to script the adding of a proxy as if it were done in the GUI, is it possible?

**Comment by Sechorda** [comment]
> > You mentioned `"mode":` should be `127.0.0.1:8080`. does this mean the proxy is always on?
> 
> Yes... that is the purpose of Enterprise Policy. It controls the extension and it is fixed. Enterprise Policy is read by the extension on browser start up and it is not possible to change it.
> 
> Please read more on the function of the Enterprise Policy. Enterprise Polices are advanced features meant for administrators.
> 
> > [storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/storage)
> > Managed data declares the enterprise policies supported by the app. Policies are analogous to options but are configured by a system administrator instead of the user, enabling the app to be configured for all users of an organization.
> 
> > If I switch `"mode":` to `disable`, where do I specify the proxy that I want available?
> 
> All `"active"` proxies are available to the extension but only the one set in the "mode" is used (unless "Proxy by Patterns) is used). You can have 100s of them listed in the `"data"`. Proxies can not be used when `"mode"` is set to `disable`. In this case FoxyProxy is disabled which means no proxying at all.

I just did a quick test, and my proxy is showing up in the 'proxy' tab under options, and the title of the proxy is hovering above the extension, but it's not listed in the proxy list and when I enable it, nothing happens.

**Comment by lap1nou** [comment]
Hey @erosman, sorry if this question was already asked but is there a way to apply a policy, but still let user modify their settings maybe ?

**Comment by erosman** [comment]
@lap1nou Enterprise Policies are meant to be fixed and only controlled by the Admin.
In v8.10 setting Tab Proxy by the user is permitted.

Other options can be explored as a different feature but browsers only load Enterprise Policies automatically.
