### ISSUE TITLE
Clicking on pattern 'filter' icon leads to import tab

### ISSUE THREAD

**Issue by mjpieters** [foxyproxy/browser-extension#17]
When editing the patterns for a proxy, clicking on the 'test' button (with blue beaker icon) leads to the _Import_ tab, no the expected _Tester_ tab.

It's a small enough fix:

```diff
diff --git a/src/content/options.js b/src/content/options.js
index 3bd176b..a0b45a7 100644
--- a/src/content/options.js
+++ b/src/content/options.js
@@ -78,7 +78,7 @@ class Options {
     // --- navigation
     this.navOptions = document.getElementById('nav3');
     this.navProxy = document.getElementById('nav4');
-    this.navTester = document.getElementById('nav5');
+    this.navTester = document.getElementById('nav6');

     // --- Incognito Access
     // https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings
```

(Note, I ran [`git config core.whitespace cr-at-eol`](https://stackoverflow.com/questions/1889559/make-git-diff-ignore-m) locally as the codebase seems to mix CRLF and LF line endings, `options.js` uses CRLF)

**Comment by erosman** [comment]
Thank you. An oversight when "import" was moved to its own tab. 

Done.
