### ISSUE TITLE
Android/Firefox - Export Patterns button doesn't appear to work.

### ISSUE THREAD

**Issue by slevit** [foxyproxy/browser-extension#18]
Tap button and nothing happens. No save location prompt. Nothing. If export file lands in some default folder, please reveal the location.

**Comment by ericjung** [comment]
Hi, you are posting in the wrong project. This project is from version 8.x and above. But that's OK. The only way to export in the current (pre-8.x version) is like this:

https://help.getfoxyproxy.org/index.php/knowledge-base/export-foxyproxy-for-chrome-settings/
