### ISSUE TITLE
Proxy basic auth

### ISSUE THREAD

**Issue by landy2005** [foxyproxy/browser-extension#19]
It seems not correctly used basic auth login/password.

I can't use with correct login/password pair.
In other places it's work, also with Firefox default proxy settings

**Comment by erosman** [comment]
> Hrm, probably trouble when proxy server not asked for basic auth.

There appears to be an issue with the [simple-proxy](https://github.com/jthomperoo/simple-proxy):
- [Basic Auth not working](https://github.com/jthomperoo/simple-proxy/issues/1)

**Comment by landy2005** [comment]
Yah, sorry for attention. Missed this issue.
