### ISSUE TITLE
Mobile FireFox and the lack of `browser.proxy.settings` API

### ISSUE THREAD

**Issue by ilyaigpetrov** [foxyproxy/browser-extension#21]
Hi, @erosman.

I see that `browser.proxy.settings` API is used in the sources.
Meanwhile this API hasn't been implemented on Android yet according to https://bugzilla.mozilla.org/show_bug.cgi?id=1725981.

Do you think the lack of this API will be a block for mobile FireFox?

**Comment by erosman** [comment]
True.... also [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings)

The main proxying in FoxyProxy is done via [proxy.onRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest) which is supported on Firefox on Android.

I will update the code to avoid errors.

**Comment by ilyaigpetrov** [comment]
To all who is interested in the future of proxying add-ons for mobile FireFox, please, sign in into https://bugzilla.mozilla.org and [vote for this API to be implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1725981) like on the image below:


![ffx-vote](https://github.com/foxyproxy/browser-extension/assets/1090811/05187c10-6225-4e38-bda5-16cb19cd3e61)

**Comment by erosman** [comment]
Added experimental Firefox on Android support
Please note that PAC URL will not be available on Android

Please let us know how it works out.
