### ISSUE TITLE
Does not work on LibreWolf (Firefox Fork)

### ISSUE THREAD

**Issue by T2JOESl4m2ZpNC** [foxyproxy/browser-extension#22]
Hello, foxyproxy v8 on Librewolf (116.0-1)  is not proxying the requests, tried it on brave and works fine

Installed it using following commands

```
cd browser-extension/src
cp manifest-firefox.json manifest.json
zip -r foxyproxy_v8.xpi .
```
then disabled xpinstall.signatures.required and loaded it from about:addons

Proxies I am using: 
 - SOCKS5 to a VPN internal wireguard socks proxy
 - Also tried TOR and a having a netcat connection on port 8080 to debug (while disconnected from the VPN) but no requests came in.
 
 Was using the old version, when installed the new one, it automatically override the old one but kept the servers.

 Things I tried:
 - Clearing/resetting and re-importing servers
 - uninstalling extension and installing again
 
![1692313845-sshot](https://github.com/foxyproxy/browser-extension/assets/96769155/ad41a1ac-1ee5-42f4-87f1-b2f5020a39f4)

**Comment by T2JOESl4m2ZpNC** [comment]
Tried Firefox (116.0.2), it's also not working , maybe this will help
![1692315516-sshot](https://github.com/foxyproxy/browser-extension/assets/96769155/9f8a9347-b216-40b0-bafd-b87bfc80701b)

**Comment by erosman** [comment]
Thank you. 
Please try the new `on-request.js` and let me know.

**Comment by T2JOESl4m2ZpNC** [comment]
Hello, 
i no longer have that error, but it is still not working

**Comment by T2JOESl4m2ZpNC** [comment]
I wanna add that the old extension + Ublock combination was leaking DNS, new one isn't, very nice

**Comment by erosman** [comment]
The code was written for Firefox & Chrome. 
`on-request.js` is used for Firefox but not for Chrome.

It is best to verify on Firefox first.
Does it work on Firefox?

- If the issue happens on Firefox as well, then it is a bug
- If the issue doesn't happen on Firefox but happen on LibreWolf, then it is a compatibility issue

**Comment by T2JOESl4m2ZpNC** [comment]
confirmed, on firefox aswell

**Comment by erosman** [comment]
Oh... there is an issue with the icon. It changes the proxy but the icon stays grey.
I will find the cause and fix it.

**Comment by erosman** [comment]
Did you allow Run in Private Windows?

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/f8529fbe-31c9-40a3-a9b8-090a6a16e53f)

**Comment by T2JOESl4m2ZpNC** [comment]
Yes, Firefox:
![1692392124-sshot](https://github.com/foxyproxy/browser-extension/assets/96769155/265fb3fe-4f3a-4905-862c-7aa1a324f1d1)

**Comment by T2JOESl4m2ZpNC** [comment]
There is also this bug, when loading addon for first time then importing/saving proxies and selecting one from the popup the icon is grayed out, the icon is greyed out. Unless i restart browser or reload extension from debugging page. (but that doesn't fix the above issue)
![1692392383-sshot](https://github.com/foxyproxy/browser-extension/assets/96769155/f7de7373-cf56-43d8-a383-1e4378261827)

**Comment by erosman** [comment]
Do yo have other proxy addons?

What does `about:preferences -> Network Settings` say?

**Comment by T2JOESl4m2ZpNC** [comment]
on Firefox is the only extension, but both says that foxyproxy is controlling how i connect to the internet

**Comment by erosman** [comment]
Can you please post STR (Steps to reproduce)?

**Comment by T2JOESl4m2ZpNC** [comment]
- git clone repo
- cp manifest-firefox.json manifest.json
- zip -r foxyproxy_v8.xpi .
- open firefox (fresh install without any addon since i don't use it)
- head to about:debugging page and load temporary addon foxyproxy_v8.xpi
- allow run in private
- got to the options and import around 300 servers by url
   > Example: socks5://us-sjc-wg-socks5-107.relays.mullvad.net:1080?cc=us&title=us-sjc-wg-107
- Save Proxies
- select one from popup (shows as grey icon)
- no request gets proxied

**Comment by ericjung** [comment]
I confirm that SOCKS proxies are not working - using wireshark, I see no traffic on the port.

**Comment by erosman** [comment]
Found it... it is an oversight affecting proxying on Firefox (not only SOCKS).
Updated `proxy.js`.
Please try and let me know.

**Comment by T2JOESl4m2ZpNC** [comment]
Hello, It is indeed fixed now.
Thank you
