### ISSUE TITLE
Feature Request - Searching from the popup

### ISSUE THREAD

**Issue by T2JOESl4m2ZpNC** [foxyproxy/browser-extension#23]
Hello

With a large list of proxies it becomes annoying to scroll looking for the location/proxy to use from the popup.
If possible a feature where maybe when hovering over the extension popup and pressing `/` for example, will allow filtering like in the options page

Thanks

**Comment by erosman** [comment]
Let's see of there is a popular demand for it.

**Comment by erosman** [comment]
Added Search filter to Toolbar popup in v8.1
