### ISSUE TITLE
Do not show disabled proxy 

### ISSUE THREAD

**Issue by Kubrix** [foxyproxy/browser-extension#24]
8.0

![image](https://github.com/foxyproxy/browser-extension/assets/33233100/7445f923-1989-4cb6-a0d8-e28335e18212)

Moreover - i think extention was unstalled after closing FF
As extention was added as temporary

**Comment by erosman** [comment]
Found it... it was an oversight. Try now.

> Moreover - i think extention was unstalled after closing FF
> As extention was added as temporary

That is the case with temporary installations.

**Comment by Kubrix** [comment]
Fixed
