### ISSUE TITLE
feature request: "add exemption rule for this website" (i.e. not "this domain")

### ISSUE THREAD

**Issue by henk84** [foxyproxy/browser-extension#27]
Hi

Coming back to my initial motivation for requesting this https://github.com/foxyproxy/firefox-extension/issues/200
some sites have stuff included that breaks when accessed via a proxy (tor in this case), i.e. not the domain one is actually accessing is giving trouble but a "third party" domain. ("third party" for lack of a better word, because it’s sometimes not actually "third party", but "first party", yet a different domain.)
Sadly, the example I thought I had seems to work fine now, so I can’t give a proper example ATM.

Would it be possible to continue having rules based on domain of the actual request but additionally allow creating rules for some of the following
* all requests made in this tab
* all requests made in the context of loading $domain (loading something like maps.google.com would also cause requests to googleapis.com and I would like to be able to tell foxyproxy to treat all requests in the context of maps.google.com with the same rule)
* all requests made by a given container

Thank you for considering!

_Originally posted by @henk84 in https://github.com/foxyproxy/firefox-extension/issues/200#issuecomment-1519987556_

ping @hideman85

**Comment by erosman** [comment]
> all requests made in this tab

**Added Tab Proxy feature (Firefox only)** (v8.0)

Subsequent to the previous discussions, I have already added the new feature.
Users can set a desired proxy to a tab and all the net requests generated from that tab will be set to that proxy.
It will remain in force until it is unset by the user, or tab is closed.

> all requests made in the context of loading $domain (loading something like maps.google.com would also cause requests to googleapis.com and I would like to be able to tell foxyproxy to treat all requests in the context of maps.google.com with the same rule)

That is not currently possible within the available browser API. The data is not provided by the API to associate "googleapis.com" with "maps.google.com" coming from the same page.

> all requests made by a given container

While it is possible to tie a proxy to a container, as mentioned in [#132](https://github.com/foxyproxy/firefox-extension/issues/132), [#194](https://github.com/foxyproxy/firefox-extension/issues/194), & [#136](https://github.com/foxyproxy/firefox-extension/issues/136), there are considerations on how it should behave. It requires further discussion.

**Comment by henk84** [comment]
> > all requests made in this tab
> 
> **Added Tab Proxy feature (Firefox only)** (v8.0)
> 
> Subsequent to the previous discussions, I have already added the new feature. Users can set a desired proxy to a tab and all the net requests generated from that tab will be set to that proxy. It will remain in force until it is unset by the user, or tab is closed.

Oh, cool, thank you!

I guess this issue can be closed, then, but I won’t do that since I’m unsure what your policy is who closes issues: the creator of the issue or the owner of the bugtracker.

**Comment by erosman** [comment]
I am planning on working on the container support feature.

We can open a new topic for the container support or keep this one.

**Comment by TriMoon** [comment]
@henk84 
> some sites have stuff included that breaks when accessed via a proxy (tor in this case), i.e. not the domain one is actually accessing is giving trouble but a "third party" domain. ("third party" for lack of a better word, because it’s sometimes not actually "third party", but "first party", yet a different domain.)

See #31 :wink:

**Comment by ericjung** [comment]
> I’m unsure what your policy is who closes issues

We are proudly policy-free in this regard 😀
