### ISSUE TITLE
[Bug] V8 Import from older version is broken.

### ISSUE THREAD

**Issue by TriMoon** [foxyproxy/browser-extension#28]
I just wanted to try this new version, so i exported my settings from the older version from "ff-add-ons" and tried to import it in this new version.
But it seems it has problems...

I have a few proxies setup with many rules that are mixed wildcard/RegExp...
![image](https://github.com/foxyproxy/browser-extension/assets/1723378/a3336005-28be-4401-883f-a3f964a86ec8)
This rule inside the backup-json looks like:
```json
{
   "title": "ipv6 adress",
   "pattern": "^\\[([0-9]|:)+\\]",
   "type": 2,
   "protocols": 1,
   "active": true
},
```
Obviously you need to fix your import functionality, if you want more people to test :wink: 
_(Because people won't want to hand edit all their rules manually...)_
> [!NOTE]
I will try to remove all the prepended `*://` or `*://*` and appended `/` from the rules to see if they still work, but i think i need to hand edit as needed..

---
> [!WARNING]
It seems these kind of default rule in the old version, seem to be broken also...
Not only because of the prepended/appended chars mentioned above, but because they were intended to check the **HOSTNAM-PART**'s only...

```json
"blackPatterns": [
{
   "title": "local hostnames (usually no dots in the name). Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
   "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?(?:localhost|127\\.\\d+\\.\\d+\\.\\d+)(?::\\d+)?(?:/.*)?$",
   "type": 2,
   "protocols": 1,
   "active": true
},
{
   "title": "local subnets (IANA reserved address space). Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
   "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?(?:192\\.168\\.\\d+\\.\\d+|10\\.\\d+\\.\\d+\\.\\d+|172\\.(?:1[6789]|2[0-9]|3[01])\\.\\d+\\.\\d+)(?::\\d+)?(?:/.*)?$",
   "type": 2,
   "protocols": 1,
   "active": true
},
{
   "title": "localhost - matches the local host optionally prefixed by a user:password authentication string and optionally suffixed by a port number. The entire local subnet (127.0.0.0/8) matches. Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
   "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?[\\w-]+(?::\\d+)?(?:/.*)?$",
   "type": 2,
   "protocols": 1,
   "active": true
},
```

---
> [!IMPORTANT]
I think you need to separate your patterns into `protocol`, `hostname`, and eventual `path` patterns in your new version, and import into the hostname patterns only.
The protocol part could be made a select-list, while the other two definitely need separate input boxes and code to check only those parts of the URL...

**Comment by ericjung** [comment]
Thank you. Do you have any wildcard patterns? Did they import successfully?

**Comment by erosman** [comment]
> ![image](https://user-images.githubusercontent.com/1723378/270193994-a3336005-28be-4401-883f-a3f964a86ec8.png) 
> This rule inside the backup-json looks like:
> 
> ```json
> {
>    "title": "ipv6 adress",
>    "pattern": "^\\[([0-9]|:)+\\]",
>    "type": 2,
>    "protocols": 1,
>    "active": true
> },
> ```

> Obviously you need to fix your import functionality, if you want more people to test 😉 _(Because people won't want to hand edit all their rules manually...)_

The error says it all. The regular expression has errors. Please fix the error and try again. `[0-9]` requires a repeat value.
FoxyProxy v8.0 checks the patterns for errors before saving them (previous versions didn't).


> Important I think you need to separate your patterns into `protocol`, `hostname`, and eventual `path` patterns in your new version, and import into the hostname patterns only. The protocol part could be made a select-list, while the other two definitely need separate input boxes and code to check only those parts of the URL...

FoxyProxy originally supported full URL matching patterns. Due to some API limitations, it was later changed to host matching patterns in the Firefox version. FoxyProxy v8.0 supports full URL patterns matching in v8.0 again.

**Comment by agamotto** [comment]
Not sure if related or not, but with extension upgrade to 8.0. my configured proxies are gone. Where can I find them and import them?

**Comment by erosman** [comment]
> Not sure if related or not, but with extension upgrade to 8.0. my configured proxies are gone. Where can I find them and import them?

Was the upgrade for FoxyProxy Basic on Firefox?
If so, it would be a different issue.

**Comment by agamotto** [comment]
> > Not sure if related or not, but with extension upgrade to 8.0. my configured proxies are gone. Where can I find them and import them?
> 
> Was the upgrade for FoxyProxy Basic on Firefox? If so, it would be a different issue.

Yes it was on Firefox (latest 117.0.1), it just updated FoxyProxy Basic automatically but configurations were gone.

**Comment by erosman** [comment]
Do you have a backup?

**Comment by TriMoon** [comment]
> Thank you. Do you have any wildcard patterns? Did they import successfully?

Yes i have many, and no they didn't import successfully as i mentioned in the OP...


> The error says it all. The regular expression has errors. Please fix the error and try again. `[0-9]` requires a repeat value.
> FoxyProxy v8.0 checks the patterns for errors before saving them (previous versions didn't but failed later when matching).

The regExp in the backup has NO-ERRORS, it is the translation while importing that has error...

> FoxyProxy originally supported full URL matching patterns. Due to some API limitations, it was later changed to host matching patterns in the Firefox version. FoxyProxy v8.0 supports full URL patterns matching in v8.0 again.

I understand that's why i suggested you to split into parts for the user and you code.
That way you can both import backups from the current old version AND allow users to explicitly enter regExp for the page parts.
- > [!Important]
I think you need to separate your patterns into `protocol`, `hostname`, and eventual `path` patterns in your new version, and import into the hostname patterns only. The protocol part could be made a select-list, while the other two definitely need separate input boxes and code to check only those parts of the URL...

Your code NEEDS 3 separate values to correctly compose the final regExp:
1. Protocol part:
This can be a string or enum in your code.
The String is in case you will allow users to enter freestyle text fe. `ws` instead of the standard `http` or `https`, otherwise you can make it an `enum` only that the user can select from a drop-down listing.
1. Host part:
This is to be able to properly import previous backups which only supported hostnames.
1. Path part:
This will be the page address after the hostname.

**Comment by erosman** [comment]
There is actually a bug in the pattern conversion. I am going to fix it.

**Comment by TriMoon** [comment]
Please keep in mind the rules i gave in OP, because people WILL have used that kind...

I'll be waiting to pull the changes and test on my side :+1:

**Comment by erosman** [comment]
Repo updated with a fix (fingers crossed).

**Comment by TriMoon** [comment]
> @erosman Repo updated with a fix (fingers crossed).

> [!WARNING]
It completely broke "Import from older versions"...
When i do it does nothing at all...

**Comment by erosman** [comment]
I tested it now and didn't get any problems.

Can you give me a JSON to test?

**Comment by erosman** [comment]
Oops.. there was a typo... repo updated

**Comment by TriMoon** [comment]
:+1: Seems it's fixed now, no errors while importing from older version backup...

Will need to check all rules later when i have time, but looks good so far :+1:

**Comment by erosman** [comment]
The log is generated from a separate independent process which doesn't have access to the saved data. It prints direct from the data provided by Firefox.

It would also be easier to correlate the log with external network monitors.

**Comment by ericjung** [comment]
The 7.x and earlier versions display the name of the proxy and it’s colors in the log, as I remember.

**Comment by erosman** [comment]
v7.* logged every connection at the time of matching, and wrote it to the disk which was a very resource intensive process. The log tab showed the data saved to the disk.

v8.0 has a live log. It starts when the Options page opens and stops when the page is closed. It does not write data to disk. It is a very resource friendly process.

Please also note ...

Proposal: Provide documentation and reporting for browser's slow extension warnings
`https://github.com/w3c/webextensions/issues/456`

> https://searchfox.org/mozilla-central/source/dom/ipc/ProcessHangMonitor.cpp#63-86
> `"EXTENSION NAME" is slowing down Firefox. To speed up your browser, stop that extension. Learn more `
> 
> https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/warning_set.cc;l=71-80;bpv=1;bpt=1
> `This extension is slowing down Google Chrome. You should disable it to restore Google Chrome's performance.`

**Comment by ericjung** [comment]
> and wrote it to the disk

https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/background.js#L14

There is no reason to write to disk unless the background page can be unloaded? It cash be kept in a 500 element in-memory array.

there were never any complaints about performance of 7.x. You are sacrificing excellent functionality — why people choose FoxyProxy— to maximize performance of an edge case. Logging is an edge case that is rarely used. But when it is used, users should be able to correlate a URL with a proxy that loads it. If I have 15 or more proxies, and multiple URLs to track down which proxy loaded it, the current log is useless because I will spend an inordinate amount of time and have to take notes on which proxy loads which url.

**Comment by erosman** [comment]
Keeping it in memory simply means in RAM disk (which often result in writing to non-RAM disk when HD is used to supplement RAM).

Furthermore, in MV3 background page will be unloaded.

Having titles for proxies is not compulsory. Personally, I never bothered with it and always used the hostname which would show exactly where the request is sent.

People with many proxies will have to memorize what each title refers to, i.e. which hostname and which port.
IMHO, that is actually worse.

The Log in v8.0 is a help tool. It does not replace a proper network monitor software which should be used for proper analysis.

**Comment by erosman** [comment]
In MV3 background page will be unloaded.
