### ISSUE TITLE
CR+LF in many files.

### ISSUE THREAD

**Issue by TriMoon** [foxyproxy/browser-extension#34]
I just noticed many, not all, of your source code files have CR+LF (`\r\n`) as line-endings, which might cause problems sooner or later.
CR+LF is a MicroShaft only encoding, all other OS's use a single LF (`\n`)...
- `find -exec file '{}' + | grep CRLF`:
_(Executed in the directory where the git repo was cloned, just now)_
```console
./src/content/about.html:                                               HTML document, Unicode text, UTF-8 text, with CRLF line terminators
./src/content/app.js:                                                   JavaScript source, Unicode text, UTF-8 text, with CRLF line terminators
./src/content/background.html:                                          HTML document, ASCII text, with CRLF line terminators
./src/content/background.js:                                            JavaScript source, ASCII text, with CRLF line terminators
./src/content/default.css:                                              ASCII text, with CRLF line terminators
./src/content/help.html:                                                HTML document, Unicode text, UTF-8 text, with very long lines (365), with CRLF line terminators
./src/content/iframe.css:                                               Unicode text, UTF-8 text, with CRLF line terminators
./src/content/options.css:                                              Unicode text, UTF-8 text, with CRLF line terminators
./src/content/options.html:                                             HTML document, Unicode text, UTF-8 text, with CRLF line terminators
./src/content/popup.css:                                                ASCII text, with CRLF line terminators
./src/content/popup.html:                                               HTML document, ASCII text, with CRLF line terminators
./src/content/popup.js:                                                 JavaScript source, ASCII text, with CRLF line terminators
./src/content/options.js:                                               JavaScript source, Unicode text, UTF-8 text, with CRLF line terminators
./src/image/bin.svg:                                                    exported SGML document, ASCII text, with very long lines (481), with CRLF line terminators
```

AFAICS, most happened due to "file upload" instead of `git push` by a member :wink: 
You might consider adding a `.gitattributes` file to fight this problem, see: https://www.git-scm.com/docs/gitattributes
_(It will also make the total smaller for distributing :rofl:)_

:vulcan_salute:

**Comment by erosman** [comment]
Actually, they are left over on some files from developing on my Windows machine. I use Linux now. I will convert those.

**Comment by TriMoon** [comment]
@erosman don't forget to create an appropriate `.gitattributes` file to prevent it getting into the repo in future :wink:

**Comment by erosman** [comment]
I don't use `git` (there is a reason for it). I upload to repo.
It will upload fine. As you have seen not all the files have CRLF.

**Comment by TriMoon** [comment]
My advise was to auto prevent for other people using `git`, that might help in future...
You are free in your choice how to submit changes, just make sure your environment doesn't use CRLF endings :wink: 

The `.gitattributes` file, when setup properly, will allow other contributors that use `git` to checkout/checking with proper line endings in future...
