### ISSUE TITLE
[Bug] Multiple Selection Shadow when dragging a proxy to sort

### ISSUE THREAD

**Issue by chromer030** [foxyproxy/browser-extension#35]
Browser: Google Chrome
Extension Version : 8.1-git

Procedure:
Select a proxy to sort by drag and drop, a shadow of multiple ones will be selected, (sort is working)

Screenshot:

![Screenshot_20231002_182905](https://github.com/foxyproxy/browser-extension/assets/13361552/bc88e436-64e3-4bc3-8994-1f65eb483f83)

**Comment by erosman** [comment]
I have seen it too... I have no idea why that happens.
It doesn't happen on Firefox.
If you click and open one of the proxies and then close it again, the issue wont happen (for a while).

I have tried to change the process a few times but that didn't change.
BTW, the drag & drop code is slightly different in v8.1 (not uploaded to repo yet).

**Comment by erosman** [comment]
Strangely enough, I tried now with the new code and it didn't happen now. 
(_Chrome version 117.0.5938.132 (Official Build) (64-bit)_)

I am going to update the repo with the new code and you can try.

**Comment by chromer030** [comment]
Fixed in : cf9bd22db85a2fca1a83d0ff675553c69438ff55

Thanks.
