### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by Doc73** [foxyproxy/browser-extension#36]
Dear Dev,
I apologize for this bug report, as I'm probably missing something.
I noticed that this new version (8.0) is unable to synchronize either with the old version (Standard) or with itself installed on other devices.
Among the Firefox functions I can't find any debugging methods.
I've never actually had an account of yours, but I've always used Firefox sync.
Maybe this possibility no longer exists or not yet?
Thanks so much anyway for the clarification.
Domenico

**Comment by erosman** [comment]
When you export FoxyProxy options in v8 (Options -> Export), What is the size of the saved JSON?

**Comment by Doc73** [comment]
17 kb

**Comment by erosman** [comment]
Thank you, so It is not a size issue.
I dont use sync so I cant test it myself but I will look into it.

**Comment by erosman** [comment]
I have tested sending sync and there is no problem.
I haven't tested the receiving end as I don't have any other device to sync with.

Please note the following in FoxyProxy v8+ ...

### Sending
- Sync data is sent out only if Sync option is enabled
- Only proxies (and their patterns), & Global Exclude data are sent for sync
- Sync data is sent when above are changed i.e. when Options are edited and saved
- Browsers send sync data periodically (not immediately)
  > [storage.sync: Synchronization process](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#synchronization_process)
  > In Firefox, extension data is synced every 10 minutes or whenever the user selects **Sync Now** in **Settings > Sync** or Firefox account. 

### Receiving
- Sync data is received only if Sync option is enabled
- Sync is received on extension start-up and when Sync data is changed (listening to sync storage change event)

**Comment by Doc73** [comment]
I have always used the Firefox sync function, even with the previous version of this plugin, and always with success.

In my tests I tried both with two versions of Firefox installed on the same machine (Firefox-esr and Firefox) and between different machines. Syncing just doesn't work!

If it helps, I use Debian as my operating system. I haven't tried on Windows yet.

For the moment I have returned to the old version of this plugin

**Comment by TriMoon** [comment]
@erosman 
> * Sync is received on extension start-up and when Sync data is changed (listening to sync storage change event)

Maybe it doesn't explicitly pull the sync data on startup, especially when upgrading from older version? :thinking: 
In other words: Explicitly trigger the sync data receiver instead of waiting for Firefox to do that.

Maybe the OP could manually toggle the Sync checkbox in the options ON->OFF->ON to see if that fixes it.
_(I also use FF-Sync only, but have no other browser to sync with at moment.)_

**Comment by erosman** [comment]
> Maybe it doesn't explicitly pull the sync data on startup...

 It does.
 Sync out is sent by Firefox.

**Comment by ericjung** [comment]
According to this[this](https://wiki.mozilla.org/Services/Sync/Addon_Sync), sync only works with addons installed from addons.mozilla.org. See “ Why is Functionality Limited to Add-ons from addons.mozilla.org” So sync is not going to work when installing 8.x locally.

**Comment by Doc73** [comment]
@TriMoon 
No, it doesn't work.
I installed this addon from Mozilla webstite

**Comment by erosman** [comment]
As pointed out by ericjung, sync works between addons installed from addons.mozilla.org.
That means, the Sync wont work for temporality installed addons.

I don't know what the situation is with Chrome Sync.

**Comment by Doc73** [comment]
@erosman 
My addon is installed from addons.mozilla.org, as I said above

**Comment by erosman** [comment]
Are you trying to Sync FoxyProxy Basic v8 with another FoxyProxy v8?

**Comment by Doc73** [comment]
Yes, sure!

**Comment by erosman** [comment]
I see.... I got it mixed up with the temporarily installed FoxyProxy v8.
Sorry about that. 

Nonetheless, Firefox sync doesn't work with temporarily installed addons (like my dev version), therefore, it is harder to find out the problem.

If you want, you can do the following to test a few things...

- Go to the Options page
- Enable Sync
- Make some changes to the Proxies (deactivating one would do)
- Click SAVE
- Open the Dev Tools (F12)
- Go to the Console tab
- Type the following and hit ENTER
```js
browser.storage.sync.get().then(console.log) 
```
- You should see some data
```
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…} }
```


Now, go to the other machine (after a while). It must have Sync enabled.
- Go to the Options page
- Open the Dev Tools (F12)
- Type the same code as above
- Check the result

**Comment by Doc73** [comment]
When I type ``browser.storage.sync.get().then(console.log)``, I see nothing!

**Comment by erosman** [comment]
It should look like this...

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/940d5a61-ad5a-4df5-8e20-f4f338c5696c)

**Comment by Doc73** [comment]
Ah, I was wrong!
I see
`
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, proxyDNS: true }
`
in both FF instances, but still no sync.

**Comment by erosman** [comment]
Good....
To verify, you only changed values in one place, right?

If so, then the data is transferred. I will check the receiving end again.

**Comment by Doc73** [comment]
Yes

**Comment by erosman** [comment]
I think, I found the problem. There is a typo in the code. 

Can you possibly do this and send a screenshot or paste the result?
You can cover or delete the private data.

Same as before, open the Dev Tools but type:
```js
browser.storage.local.get().then(console.log) 
```

**Comment by Doc73** [comment]
![Schermata del 2023-10-22 22-00-12](https://github.com/foxyproxy/browser-extension/assets/1306260/7bbea33c-a709-45f3-8945-68ad8f2cdd61)

**Comment by erosman** [comment]
That is it.... it is the typo. :man_facepalming: 

It is fixed now for v8.1.
Sorry about that and thank you for helping out. :+1:

**Comment by Doc73** [comment]
Great! I' wait for new version!

**Comment by erosman** [comment]
FoxyProxy Basic 8.1 will be uploaded later on today.
