### ISSUE TITLE
Network detection feature.

### ISSUE THREAD

**Issue by R0Z-Z** [foxyproxy/browser-extension#37]
Hello,

I make use of foxyproxy for people that work remotely, and seldom coming to office. Unfortunately, I could not make them care for changing foxyproxy to patterns mode when they leave our office. Is it possible to add a network detection method that conditionally changes proxies or turn it off? I mean, for example: if in 192.168.32.0/24 turn off. If not in 192.168.32.0/24 use patterns mode.

If this is acceptable as a feature request, I'd really appreciate to see such a thing in foxyproxy. Thank you for this great useful tool. You make a sysadmin's life easier.

All the best... :)

PS: I'd like to donate what I can, however, Paypal does not work in my country. Perhaps you might think adding USDT or BTC wallet info for donations.

**Comment by erosman** [comment]
FoxyProxy 8+ has a "Global Exclude" option. By setting the IP in the Global Exclude, that IP would never be proxied, so whatever the FoxyProxy mode, it will go direct to `192.168.*.*`

ATM, CIDR is supported in some options.

Look at what the upcoming v8.1 (under development) would have under [Global Exclude](https://foxyproxy.github.io/browser-extension/src/content/help.html#global-exclude) and see if that would work for your situation.

**Comment by R0Z-Z** [comment]
If I have correcty understood this Global Exclude feature, I doubt it would exactly match my need. Yes, it may solve the problem to some extent, leaving foxyproxy always in pattern matching mode and globally excluding office network could work if I was not actually trying to reach some internal network addresses through the local socks proxy. Correct me if I am wrong.

Let me clarify some more: In my case, I use a putty localhost socks proxy that connects to my office network. And I selectively redirect some internal or external addresses using pattern matching through the local proxy. What I need is, when some previously specified network is not detected, pattern matching mode should automatically switch on; and when detected, should turn off. Or may be, when some other network is detected, another proxy profile takes over.. For example, at home network, use tor proxy setup that is served from my router. This might add quite some config flexibility for admins, and lessen clueless users' requests that forgot to switch to pattern matching mode when outside office.

Well, this might be a bit far fetched considering this extension's scope; anyways, no harm done by asking I guess.. :)

**Comment by R0Z-Z** [comment]
Ok, I get it. I'll try to figure out some other ways to deal with this problem in case it becomes unbearable. Have a nice day Eric, thank you for your time.

**Comment by TriMoon** [comment]
@ericjung 
> Unfortunately, i am not aware of a way to obtain the current LAN ip address from Firefox/Chrome web extension API.

Wouldn't it be possible to use a "Connectivity check" instead, which if succeeds enables/disable the respective proxy instead?

For example:
When in office, you could check for a special address+page accessible only in that network.
In his OP example, if a webserver in `192.168.32.0/24` responds the proxies could be considered "disabled".
Otherwise the rule to enable/disable a certain proxy would not apply and thus function as configured.

**Comment by ericjung** [comment]
Yes, that would work. Of course, it requires the user to host a web server and setup firewall rules so it’s only accessible on their intranet.

**Comment by TriMoon** [comment]
Well the OP said it was an office network, so most likely they already have one.
But for other "home" users, they could check their modems login page for instance...
