### ISSUE TITLE
Extension functionality is broken for non-PAC proxies

### ISSUE THREAD

**Issue by chromer030** [foxyproxy/browser-extension#41]
Hello, Thanks for efforts in making this extension better and better.

I tested latest git on Chrome, it doesn't work on anything else than PAC.

Selecting PAC proxies are working but by selecting any normal proxiy nothing happens

**Comment by erosman** [comment]
I updated the repo today. Was that the version that you tested?

**Comment by chromer030** [comment]
Tested and confirm it fixed in 2e2033245317bee04e210d4200f8917ff2c02e54

Thanks very much.

**Comment by chromer030** [comment]
@erosman 
Now Direct is broken, proxies all work except Direct.

**Comment by erosman** [comment]
Thank you. 
I am reworking some parts of the code. I will check that.

**Comment by chromer030** [comment]
Tested, extension is broken again completely in latest git, PACs are also broken :

https://github.com/foxyproxy/browser-extension/assets/13361552/c5aae7c9-5eac-49c3-8309-95a8c4509369

**Comment by chromer030** [comment]
Randomly hard reset to this commit 0056c56002e30f76f067eb123281eefb67df1b17 and all proxies are working.

`git reset --hard 0056c56002e30f76f067eb123281eefb67df1b17
`

**Comment by erosman** [comment]
> Tested and confirm it fixed in [2e20332](https://github.com/foxyproxy/browser-extension/commit/2e2033245317bee04e210d4200f8917ff2c02e54)

That commit was from Nov 9, 2023

> Randomly hard reset to this commit https://github.com/foxyproxy/browser-extension/commit/0056c56002e30f76f067eb123281eefb67df1b17 and all proxies are working.

Above commit is from Oct 18, 2023.

What was the last commit that was working?
What is broken exactly?
Can you select proxies?

**Comment by chromer030** [comment]
Now i tried with latest commit : 29ab2e4ce10e06e126c623207c095ed1fa26861e and really something is wrong, i thought maybe the backup file makes the issue, so tested with following procedures:

1- Git clone & rename `chrome-manifest.json` to `manifest.json` & remove other manifests.
2- Chrome > about:extensions > Pack Extension
3- Install generated `src.crx`
4- Add an example Socks5 proxy
5- Add and example Direct proxy
6- Select proxies
7- none of them work, proxy doesn't apply (IP is local)


https://github.com/foxyproxy/browser-extension/assets/13361552/800eda10-74fb-449d-b475-b99c44a11b5b

> What is broken exactly?
Proxies doesn't apply.

> Can you select proxies?
No, this is exactly the issue as you can see in recorded video:

https://github.com/foxyproxy/browser-extension/assets/13361552/c5aae7c9-5eac-49c3-8309-95a8c4509369

**Comment by erosman** [comment]
I am not sure  if it is the issue, but can you try to install the extension according to the [Installation Guide (for testing)](https://github.com/foxyproxy/browser-extension#installation-guide-for-testing) i.e. "Load Unpacked".

**Comment by chromer030** [comment]
Still the issue persists, watch the whole process:


https://github.com/foxyproxy/browser-extension/assets/13361552/6e7cf1cc-b0cf-44d5-a01f-f5833f2e5f43

Please pay attention to foxyproxy icon on toolbar when i change the proxies, nothing changes there!, means proxy switch is broken.

**Comment by erosman** [comment]
Sorry about that.. there is a bug in the latest update. Please try now.

**Comment by erosman** [comment]
Sorry about that.. there was a bug in the previous update. Please try now.

**Comment by chromer030** [comment]
> Please try now.

Tested, Working & no issue.

Appreciate your efforts.
