### ISSUE TITLE
Prompt for SOCK5 authentication when accessing site via proxy

### ISSUE THREAD

**Issue by z0id** [foxyproxy/browser-extension#43]
Hi, 

I have a SOCKS5 proxy set up with authentication. I noticed the connection works if I save the credentials in FoxyProxy, but fails if credentials are not set. 

I am in the position where I need authentication, but can't have the credentials permanently saved in the browser either. Would it be possible for FoxyProxy to have the option prompt for credentials when site is accessed, similar to the way HTTP Proxy works in vanilla Firefox?

Thanks!

**Comment by erosman** [comment]
Unfortunately, the authentication prompt comes from [webRequest.onAuthRequired](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired) and that API only handles HTTP/HTTPS/WS/WSS.
