### ISSUE TITLE
[UI] Button to directly open the Logs screen

### ISSUE THREAD

**Issue by TriMoon** [foxyproxy/browser-extension#44]
As mentioned in https://github.com/foxyproxy/browser-extension/pull/38#issuecomment-1773953561:

> Just a request, could you guys add a button on the popup to directly open the logs view like we have on the old version? 🤝
> I wasn't able to do it because i'm too unfamiliar with the JS code, in particular i went as far as just adding the button on the popup and opening the options page but i didn't know how to make the button open the view directly...

**Comment by erosman** [comment]
Adding the button is not a problem but there may not be a lot of room.

FoxyProxy 7 has 3 buttons: Options, What's My IP, and Log
FoxyProxy 8 already has 3 buttons: Options, Location, IP

Although "Log" is a short word in English, it may not be short in other languages:

ES: "Registros"
FA: "گزارشات"
FR: "Journal"
PL: "Dziennik"
PT:  "Registro"
RU: "Журнал"
CN: "日志"
... etc

**Comment by TriMoon** [comment]
IMHO, in this case the easy access to the functionality is more important as space used in the PopUp...
You could even, if needed, make the button row become 2 rows..

**Comment by erosman** [comment]
People use Location & IP to test if the proxy is working and/or if the browser is leaking the real IP.

If there is not enough room, it can mess up the layout, only to reduce 2 clicks to one.

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/86edb2e1-0da4-4501-a4d2-89481a131e8a)

BTW, you can bookmark the Log tab which is even more efficient as it doesn't require opening of the popup.

- Options the options page
- Add log at the end of the URL i.e. `.../options.html?log`
- Bookmark that page

**Comment by erosman** [comment]
v8.9
Added "Log" to the toolbar popup buttons
