### ISSUE TITLE
Proxy bypassing stopped working in new version 

### ISSUE THREAD

**Issue by athulnath** [foxyproxy/browser-extension#48]
proxy bypassing was working before, but after the update it stopped working.

proxy Type: HTTP Or WPAD URL in PAC URL
rule: 
Include: Exclude
Type: Wildcard
pattern: *.mydev.team

all URLs which follow the patterns are not by-passing. still hitting the proxy 

chrome version: 119.0.6045.199
foxyproxy: 8.1

**Comment by erosman** [comment]
Are you trying to set a global bypass?

**Comment by erosman** [comment]
Global exclude has been updated and no longer has a type.

Are you setting it under Global Exclude?

<img src="https://github.com/foxyproxy/browser-extension/blob/main/screenshots/8.1/light-theme/options-tab.jpg?raw=true" alt="">

**Comment by athulnath** [comment]
No. it got worked after putting here as you suggested. 

we were adding rules under proxies tab. please find the screenshot below. 

![image](https://github.com/foxyproxy/browser-extension/assets/7171308/1b143ff2-ec0f-4d67-a7ae-16db62bc36b9)

**Comment by erosman** [comment]
Exclude pattern under individual proxy only applies to that proxy (and not for PAC) and only when "Proxy by Patterns" is selected.

Global exclude is global.

**Comment by athulnath** [comment]
Got it.
is it possible to add WPAD URL as PAC?

I am not able to see "Proxy by Patterns" option 

![image](https://github.com/foxyproxy/browser-extension/assets/7171308/ad14ea4a-eec0-41b5-bf14-9758e41c9278)

how can I enable it?

**Comment by erosman** [comment]
> is it possible to add WPAD URL as PAC?

If there is a test WPAD, I can work on it.

> I am not able to see "Proxy by Patterns" option

If there aren't any patterns set for any active proxies, users wont be able to select "Proxy by Pattern" and the option is hidden to avoid confusion.

**Comment by athulnath** [comment]
got it. 
I am able to see it now
Thank you.
