### ISSUE TITLE
PAC URL file:/// Unsupported 

### ISSUE THREAD

**Issue by 20NE** [foxyproxy/browser-extension#49]
foxyproxy standard 8.2
firefox support local pac file. but foxyproxy seems doesn't support it 
When fill PAC URL field with: file:///path/to/pacfilename.pac
error: `Unsupported Protocol file:`

**Comment by belperite** [comment]
Hi @erosman I'm just trying a file: PAC URL on 8.6, and I can't get it to save - a red outline appears around the field and clicking save does nothing :( Please see screenshot
<img width="1164" alt="Screenshot 2023-12-13 at 11 51 23" src="https://github.com/foxyproxy/browser-extension/assets/33836503/de64bb99-f1b4-4504-8837-1de859a62810">

**Comment by erosman** [comment]
You are right. There is another issue with using `file://` for PAC URL.
I will fix it for v8.7.

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.

**Comment by directentis1** [comment]
Hi, I'm in the same boat.
When tried to load a PAC file from my Ubuntu. 
I got `TypeError: NetworkError when attempting to fetch resource.` when click View.

![Image](https://github.com/user-attachments/assets/04cf11bd-20f3-49bc-bfd4-97fb53e8e919)

**Comment by directentis1** [comment]
Well, in my use case, I just need to update hostname dynamically because my local VPN wrapper use tap interface, so it generates a random IP in range 169.254.0.0-169.254.255.255.

Maybe local PAC file doesn't resolve that issue.

Is there any dynamic way to update FoxyProxy config by script?

**Comment by erosman** [comment]
@directentis1 Are you trying to load a PAC from `file:///...` on Firefox?
Firefox does not allow loading files from the local file system.
Chrome allows it for an extension via "Allow access to file URLs" option.

The easier workaround is to run a local mini web-server.

`python` has the option to run a mini web-server 
[http.server — HTTP servers](https://docs.python.org/3/library/http.server.html)
[Ubuntu 20.04 best way to make file server?](https://askubuntu.com/questions/1316298/ubuntu-20-04-best-way-to-make-file-server)
[How do I set up the simplest HTTP local server?](https://askubuntu.com/questions/1102594/how-do-i-set-up-the-simplest-http-local-server)
[Run a web server from any directory](https://askubuntu.com/questions/520602/run-a-web-server-from-any-directory)

You can also set up a minimal web-server with `npm`.

**Comment by erosman** [comment]
@directentis1 Are you trying to load a PAC from `file:///...` on Firefox?
Firefox does not allow loading files from the local file system.
Chrome allows it for an extension via "Allow access to file URLs" option.


You might be able to set a static IP.
[How to create a persisted TAP interface with static IP address?](https://forum.manjaro.org/t/how-to-create-a-persisted-tap-interface-with-static-ip-address/151697)

You can also run a local mini web-server.

`python` has the option to run a mini web-server 
[http.server — HTTP servers](https://docs.python.org/3/library/http.server.html)
[Ubuntu 20.04 best way to make file server?](https://askubuntu.com/questions/1316298/ubuntu-20-04-best-way-to-make-file-server)

You can also set up a minimal web-server with `npm`.

**Comment by directentis1** [comment]
@erosman Hmm, I have had read this discussion, but because tap interface is ephemeral, it'll be destroyed and recreated each time I restart the proxy service.
And NetworkManager doesn't show up option to manually modify it 
Preharp should be a way to do that, I will try to find out. 🤔

**Comment by erosman** [comment]
@directentis1 BTW, the PAC with `file://` should work.

While the `View` is not allowed to fetch from local file system, setting a PAC in FoxyProxy sets it directly in the browser and there, `file://` should work.

**Comment by directentis1** [comment]
@erosman Got it!!
Btw, I just want to ask, does PAC option can't be set for each individual tab?
So... it will be affect all the Firefox, not like an option to choose and separate one.
