### ISSUE TITLE
Authenticated SOCKS5 proxy not working in Chromium

### ISSUE THREAD

**Issue by unrealtournament** [foxyproxy/browser-extension#52]
I have installed the extension on the latest Chromium (`Version 120.0.6099.71 (Official Build) (64-bit)`), after adding a SOCKS5 proxy with user/pass authentication and enabling it all connections fail with the following message.
 
![image](https://github.com/foxyproxy/browser-extension/assets/111871385/b0440f9a-92f5-413b-b459-c05938823e74)

The proxy is from Private Internet Access (more information on hostnames/IPs/ports here https://helpdesk.privateinternetaccess.com/kb/articles/do-you-offer-a-socks5-proxy), I've exported my working configuration from Firefox and imported it into chromium, so **the proxy itself is working just fine on the same version of FoxyProxy on Firefox**. I've also tried the proxy manually with `curl` and it works fine as expected.

Here is another screenshot showing the exact same FoxyProxy config on both Firefox and Chromium, and the proxy only working with Firefox:

![image](https://github.com/foxyproxy/browser-extension/assets/111871385/0c803308-24e9-484b-b5fd-13bedac96de7)

Things I've tried without success:

- Reinstalling Chromium
- Creating a new fresh Chromium profile
- Disabling/enabling WebRTC in Chromium flags and extension checkbox
- Disabling/enabling Proxy DNS
- Reinstalling the extension
- Adding the proxy manually instead of importing FoxyProxy settings from Firefox

If there is any additional log or information I can provide I'd be happy to do so. OS is Windows 10 x64.

**Comment by ericjung** [comment]
I am fairly sure Chrome never natively supported authentication with SOCKS5 servers. If so, username/password should be disabled on chrome when SOCKS5 server is setup or imported from Firefox; it has to be supported by the browser for it to work.

I will double-check this and reply again.

**Comment by erosman** [comment]
Chrome never supported SOCKS5 authentication. In fact, Firefox is the only browser that has an API to support SOCKS5 authentication.

It is outlined in [FoxyProxy Help](https://foxyproxy.github.io/browser-extension/src/content/help.html) under "Proxy Authentication".

FoxyProxy 8 has a unified code on Chrome & Firefox, enabling users to import/export settings between browsers. 

- Removing the data when importing would interfere with sharing between browsers
- Removing the data would also interfere with proxy type switching
- Removing the UI in Chrome will affect editing and sharing between browsers
- Disabling the UI can result in user/pass showing in imported settings and no way to edit it

**Comment by randomstuff** [comment]
For reference see [Proxy support in Chrome](https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md#socksv5-proxy-scheme):

> No authentication methods are supported for SOCKSv5 in Chrome (although some do exist for the protocol).

**Comment by ericjung** [comment]
> Chrome never supported SOCKS5 authentication. In fact, Firefox is the only browser that has an API to support SOCKS5 authentication.
> 
> It is outlined in [FoxyProxy Help](https://foxyproxy.github.io/browser-extension/src/content/help.html) under "Proxy Authentication".
> 
> FoxyProxy 8 has a unified code on Chrome & Firefox, enabling users to import/export settings between browsers.
> 
> * Removing the data when importing would interfere with sharing between browsers
> * Removing the data would also interfere with proxy type switching
> * Removing the UI in Chrome will affect editing and sharing between browsers
> * Disabling the UI can result in user/pass showing in imported settings and no way to edit it

We can warn the user when importing into chrome settings with a socks proxy server with authentication. If we don’t do anything at all (like now), I expect more tickets like this in the future.

**Comment by erosman** [comment]
> We can warn the user when importing into chrome settings with a socks proxy server with authentication. If we don’t do anything at all (like now), I expect more tickets like this in the future.

I will update the UI for v8.5
