### ISSUE TITLE
Toolbar popdown UI feels more bulky since the update

### ISSUE THREAD

**Issue by ThiefMaster** [foxyproxy/browser-extension#54]
![image](https://github.com/foxyproxy/browser-extension/assets/179599/9a78f38c-4db6-4af8-8dc8-198fb0b52a23)

I think the previous one was much more compact... maybe a setting to get a compact popdown would be nice (I usually just switch between off/patterns and sometimes forcing a proxy for all urls)

There's also a strange white thingy around the colored dot in the icon.

**Comment by erosman** [comment]
FoxyProxy 8 has many new features and capabilities, most of which were specifically requested by the users (refer to Changelog for more info).

New features require the corresponding user-interface.

**Comment by erosman** [comment]
v8.9
Added toggle more options on toolbar popup
