### ISSUE TITLE
Firefox starts very slowly with "proxy by pattern" after the big FoxyProxy update

### ISSUE THREAD

**Issue by fillest** [foxyproxy/browser-extension#55]
I have a lot of tabs (hundreds). Previously Firefox started quite fast, maybe ~6 seconds. After the big FoxyProxy update it starts for about 3 minutes.
I use "proxy by pattern" and have several dozens of simple wildcard domain rules like `*://*.medium.com/` (I remember them to be shorter/simpler before the update though..). If I use unconditional usage of proxy or just "disabled", Firefox starts fast again.

**Comment by erosman** [comment]
Is that the same after restarting Firefox?

If so, try the following:

- Export FoxyProxy settings
- Remove FoxyProxy
- Restart browser to clear its cache
- Reinstall FoxyProxy
- Import your settings

**Comment by fillest** [comment]
I exported the patterns, removed the addon, restarted, installed, re-created the proxy, imported the patterns. It didn't help.
I have also noticed that Gmail is freezing for some time. Each time it loads the interface but then all operations (e.g. clicking on "mark unread" or different mails) block for, like, maybe ~20 seconds. Then it begins to work fine again.

**Comment by 5j9** [comment]
> I exported the patterns, removed the addon, restarted, installed, re-created the proxy, imported the patterns. It didn't help. I have also noticed that Gmail is freezing for some time. Each time it loads the interface but then all operations (e.g. clicking on "mark unread" or different mails) block for, like, maybe ~20 seconds. Then it begins to work fine again.

I have similar problem on some websites on Firefox, including Google search results. Tabs become unresponsive for short periods of time, then start working again. This mostly happens when I use [Vimium C](https://github.com/gdh1995/vimium-c) keyboard shortcuts. Disabling one of the extension (FoxyProxy or Vimium) seems to fix it, but I can't think of how these two are related.

**Comment by ericjung** [comment]
> > I exported the patterns, removed the addon, restarted, installed, re-created the proxy, imported the patterns. It didn't help. I have also noticed that Gmail is freezing for some time. Each time it loads the interface but then all operations (e.g. clicking on "mark unread" or different mails) block for, like, maybe ~20 seconds. Then it begins to work fine again.
> 
> I have similar problem on some websites on Firefox, including Google search results. Tabs become unresponsive for short periods of time, then start working again. This mostly happens when I use [Vimium C](https://github.com/gdh1995/vimium-c) keyboard shortcuts. Disabling one of the extensions (FoxyProxy or Vimium) seems to fix it, but I can't think of how these two are related.

Do you also have hundreds of tabs open, or do you see this problem with fewer numbers of tabs, too?

**Comment by 5j9** [comment]
> Do you also have hundreds of tabs open, or do you see this problem with fewer numbers of tabs, too?

I have 10-30 tabs open most of the time, but the unresponsiveness occurs even with a few (4-5) tabs.

**Comment by ericjung** [comment]
> > Do you also have hundreds of tabs open, or do you see this problem with fewer numbers of tabs, too?
> 
> I have 10-30 tabs open most of the time, but the unresponsiveness occurs even with a few (4-5) tabs.

Thank you. Can you share your patterns (even privately) so I can reproduce this and debug it? You can send to support@getfoxyproxy.org and write Git ticket #55 in the subject. I can also provide you with my personal email address or telegram channel if you prefer.

**Comment by 5j9** [comment]
Sorry for the late reply. Today my FoxyProxy was automatically updated to Version 8.6 and the issue disappeared. To make sure it was the update that fixed the issue I downgraded to [8.3](https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/versions/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser) and then upgraded again, and did this several times and every time 8.3 showed noticable momentary unresponsiveness but 8.6 works fine. I'm positive the upgrade has resolved the issue. I can still send my patterns if you think it will help.

**Comment by fillest** [comment]
Oh, I didn't notice the update. Indeed I have 8.6 now and the problem is gone (both with the startup and gmail).
