### ISSUE TITLE
[Improvement] Bring back the display of disabled templates in the popup window

### ISSUE THREAD

**Issue by nlboom** [foxyproxy/browser-extension#56]
A handy feature of this extension has disappeared in newer versions. I use several proxy templates, most of the time they are disabled, but sometimes I need to enable forced proxying from a specific template for all addresses. In FoxyProxy 7.5.1 this could be done in a popup window, in 8.2 the template is not shown if it is turned off. Now I have to go to the settings and turn on the template there first and then in the popup window, which is inconvenient
- FoxyProxy Standard 8.2
- Windows 10 22H2
- Firefox 120.0.1

**Comment by erosman** [comment]
There were other users, with 10s of disabled proxies, who requested the removal of disabled proxies from the popup UI as it caused clutter and lengthy scrolling to find the right proxy.

> sometimes I need to enable forced proxying from a specific template for all addresses. 

There should be no need to disable a proxy that is used "for all addresses". Such proxy would not need any patterns and therefore it wouldn't interfere with other operations by being enabled.

**Comment by nlboom** [comment]
I think you should add a function to the template settings to display yes/no disabled proxy in the selection window.

**Comment by erosman** [comment]
There is no function in the popup to enable disabled proxies, even if they are displayed in the popup.
Would there be a use to show them?

**Comment by erosman** [comment]
There is no mechanism to enable a disabled proxy from the toolbar popup. It will only be there for show.

What would be the benefit of creating additional options in the settings and displaying the disabled proxies on the toolbar popup?
