### ISSUE TITLE
Firefox Android: Proxies are not applied on v8.2

### ISSUE THREAD

**Issue by AgentConDier** [foxyproxy/browser-extension#60]
Regardless of FoxyProxy configuration, no connections attempt to use any proxy server.

Firefox Nightly 122.0a1 (Build #2015990567), a2268afaa0+
Huawei Mate 20 Pro, Emui 12 (Android 10)
My FoxyProxy was updated to 8.2 today, before that everything has always worked fine.
Unfortunately, I don't know which version I had previously, and sideloading other versions to test is impossible on android as far as I know.

**Comment by erosman** [comment]
> **Firefox on Android**
> 
> Support is experimental and based on user feedback.

Have you enabled Run in private browsing?

**Comment by AgentConDier** [comment]
Yes, that is enabled. I am primarily using FoxyProxy in normal browsing mode though.

**Comment by erosman** [comment]
I asked since Firefox requires it and blocks the extensions without it.

**Comment by erosman** [comment]
Out of curiosity, can you try v8.3?
FoxyProxy Basic (same code) is available now.
FoxyProxy (standard) is awaiting approval.

**Comment by AgentConDier** [comment]
Using v8.4, I still can't get it to connect with a proxy server. Using pattern mode or selecting a specific proxy, the requests appear in the log but the proxy columns are empty.

**Comment by erosman** [comment]
My guess is that one of the APIs used is not supported in Firefox for Android.

If you can list what works and what doesn't, maybe I can pinpoint it and work out a workaround. 

- Single Proxy
- Proxy by Patterns
- Tab Proxy
- Incognito
- Containers

**Comment by erosman** [comment]
I think, I have found the problem.

**Comment by dmitry-j-mikhin** [comment]
FoxyProxy Basic v8.6 and Firefox 120.1.1 for Android.
Tab Proxy mode only works for me, all other options do not work.

**Comment by erosman** [comment]
## Install Firefox Nightly for Developers

- Install [Firefox Nightly for Developers](https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=en&gl=US)
- Go to: Nightly menu -> Settings ->  About Firefox nightly
- Tap a few times on the Firefox icon to enable debug menu

## Disable Automatic Updates

- Go to: `about:confog`
- Find `extensions.update.enabled`
- Toggle to `false`

## FoxyProxy Beta

- Follow [Beta Installation Guide](https://github.com/foxyproxy/browser-extension#beta-installation-guide)
- Create a zip file from the content of `src`
- Make the file available to the Android device

## FoxyProxy Older Versions

- Go to: https://addons.mozilla.org/firefox/addon/foxyproxy-standard/versions/
- Download the desired version

## Install add-on from file

- Go to:  Android Nightly menu -> Settings -> Advanced -> Install add-on from file

**Comment by AgentConDier** [comment]
Thanks, I didn't know about that debug mode.
I can confirm that v7.5.1 works as expected.
When I try to install the latest beta (64598b1b438ab512825ee1abfc89f28d650efda9), it refuses with ‘This add-on could not be installed, because it hasn't been verified’. Is that a known restriction for Android, or am I packaging it wrong?

**Comment by AgentConDier** [comment]
Firefox Nightly for Developers

**Comment by erosman** [comment]
hm... I am going to ask Mozilla and get back to you.

**Comment by AgentConDier** [comment]
Yes, that did it. I've installed the beta version now, firefox shows it as v8.7
Proxies still only work when set as per-tab proxy though.

**Comment by erosman** [comment]
BTW, you can install older version in normal Firefox for Android as well (for your normal use), after enabling debug menu.

You can use Nightly only for beta testing.
I am asking Mozilla if there is a log in the Nightly for Android to see where the error is.

**Comment by erosman** [comment]
After having a chat with Mozilla, I have found the problem. :crossed_fingers: 
The API test did not work as expected and caused the error.
Try v8.7 now.

**Comment by AgentConDier** [comment]
Hmm it still isn't using the proxy server unless I set it as the tab proxy

**Comment by erosman** [comment]
Thank you for testing. 
Did you test it with the latest update of the repo?

I will check it again.

**Comment by AgentConDier** [comment]
Yes, I reinstalled from a zip file of 00c8670eb9663be757a6a9832b7bff21e53a2e69

**Comment by pggdt** [comment]
I'm on Android with Fennec and Mull which are both base on Firefox Mobile. Version 8.6 not working on them. Thank you for your hard working, and we are looking forward to updating them with a working Foxyproxy.

**Comment by erosman** [comment]
I updated the repo with the fix and I tested it on Android and it was working.
Please let me know if there are any issue.

**Comment by AgentConDier** [comment]
Yes, it's working now (2d8cfad87913030490a139626466c93e66e4308f)! Thanks a lot for putting in the effort 👍

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.
