### ISSUE TITLE
[UI] The disabled icon has white color backgroud, which looks ugly in dark theme

### ISSUE THREAD

**Issue by hyh19962008** [foxyproxy/browser-extension#61]

**Comment by selim13** [comment]
![foxyproxy1](https://github.com/foxyproxy/browser-extension/assets/10496/b35175c7-c8be-49ac-81ab-17e9236d8afa)
![foxyproxy2](https://github.com/foxyproxy/browser-extension/assets/10496/75ae0110-5cf2-4406-b300-1f0a24e6a72e)

Both "Disable" and "Proxy by pattern" have incorrect icon background on dark themes.

**Comment by erosman** [comment]
I will work something out for the next update v8.4

**Comment by erosman** [comment]
I have looked into dark theme detection and sadly, it wont work in Chrome's background script.
I am checking to see if there is an alternative method.

**Comment by erosman** [comment]
I got it working and it is done for v8.4

**Comment by erosman** [comment]
It is done in v8.4
We are uploading v8.4 to AMO.
FoxyProxy Basic (same code) will be available shortly but FoxyProxy (standard) will take time due to the AMO review process.
