### ISSUE TITLE
Backward compatibility with older configs

### ISSUE THREAD

**Issue by Ponywka** [foxyproxy/browser-extension#62]
Why new update of FoxyProxy for Firefox breaks backward compatibility with older configuration stored in browser data?

I'm lucky because I have backup on "MS Windows" partition so I can restore this info from other location but WTF?

Only 30 seconds for backup. People who use our extension even can't know about your update and lost their configurations!!!

https://www.youtube.com/watch?v=0y86SRQVj6E

Update: Solution here: https://github.com/foxyproxy/browser-extension/issues/62#issuecomment-1848448675

**Comment by Ponywka** [comment]
Also return back "Synchronize Settings" with Mozilla account please

![image](https://github.com/foxyproxy/browser-extension/assets/26777464/932768a6-3ea5-494b-8371-242b443f85fa)

**Comment by erosman** [comment]
Please note https://github.com/foxyproxy/browser-extension/issues/53#issuecomment-1848282804

**Comment by erosman** [comment]
> Also return back "Synchronize Settings" with Mozilla account please

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/0dbb6a38-6fe4-420b-aec5-955d628b169e)

**Comment by Ponywka** [comment]
> > Also return back "Synchronize Settings" with Mozilla account please
> 
> ![image](https://private-user-images.githubusercontent.com/6458876/289285668-0dbb6a38-6fe4-420b-aec5-955d628b169e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzgxNTYsIm5iZiI6MTcwMjEzNzg1NiwicGF0aCI6Ii82NDU4ODc2LzI4OTI4NTY2OC0wZGJiNmEzOC02ZmU0LTQyMGItYWVjNS05NTVkNjI4YjE2OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTYwNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE5ODEyNGI3Y2Y1NmFmMzhiMDllZGUzZTJjMDY3NWQwYWEwM2I3MDUzZDU4ODI0ZDE1MjA4ZDIzMTA4ZDM2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tg3Jq0VlWDmCAnFY65NHX-3rqQFlZFYLAyl6r9LKFPc)

Oh... I'm sorry :(
