### ISSUE TITLE
does not recognize 'no proxy for' setting (in Firefox) properly

### ISSUE THREAD

**Issue by tmeidinger** [foxyproxy/browser-extension#63]
Browser: Firefox 120.0.1
OS: macOS 14.2

If e.g. 192.168.0.0/24 is set in the Firefox 'no proxy for' setting. FoxyProxy 8.2 is not proxying for 192.168.\*.\*.

**Comment by erosman** [comment]
Do you mean "No proxy for" in `Settings -> Network Settings -> Connection Settings`?

That setting is only applicable when setting a Remote PAC.

Try setting it in  [Global Exclude](https://foxyproxy.github.io/browser-extension/src/content/help.html#global-exclude).

**Comment by tmeidinger** [comment]
The network on the LAN is 192.168.0.0/24 and version 8.2 doesn't proxy 192.168.178.* any more. Regex rule is ^https?://192\.168\.178(\.\d+) (not working) but e.g. ^https?://10\.0\.0(\.\d+) is working. Even if I am selecting the proxy manually (for all traffic) it's showing in the log 192.168.178.1 is not sent to the proxy.

I downgraded to version 7.5.1 and everything is fine again.

**Comment by erosman** [comment]
192.168.0.0/16 is set as global exclude in FoxyProxy in Firefox since it is local network.

Do you want to go to 192.168.0.0/16 via a proxy?

**Comment by tmeidinger** [comment]
192.168.0.0/24 is the local network. I want to go to 192.168.178.0/24 via a proxy.
https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing

**Comment by erosman** [comment]
Previously: #50

**Comment by tmeidinger** [comment]
It seems to me as if this is a different issue. Localhost 127.0.0.1/8 is a different issue from 192.168.0.0/24 not being 192.168.0.0/16.

**Comment by erosman** [comment]
FoxyProxy 8 is hardcoded to bypass proxy for localhost and local networks.
192.168.0.0/16 is often used for Wi-Fi modem/router and they shouldn't really be proxied.

Topic #50 is a discussion topic for the local network bypass.

**Comment by tmeidinger** [comment]
The internet is classless. If I'd like to route 192.168.0.0/30 (on the internal network) that's ok with every RFC I know. The same goes for proxying. There is absolutely no reason to exclude rfc6761 (former rfc1918) IP space.

**Comment by erosman** [comment]
I am discussing the issue with the founder of FoxyProxy and some or all of localhost checks will be removed in v8.4

**Comment by erosman** [comment]
It is done in v8.4
We are uploading v8.4 to AMO.
FoxyProxy Basic (same code) will be available shortly but FoxyProxy (standard) will take time due to the AMO review process.
