### ISSUE TITLE
Unauthenticated socks5 proxies with server localhost, targetting localhost dns addresses appear not to work in version 8.2

### ISSUE THREAD

**Issue by alexisatkinson** [foxyproxy/browser-extension#64]
Socks5 proxies proxying localhost appear not to work when upgrading to version 8.2.

I've tested this on Ubuntu 22.04 using Firefox 120.0.1.

when targetting any website other than localhost, there are no problems.

However, when targetting localhost, this doesn't work.

Reverting back to version 7.5.1 immediately fixes the issue

Steps to replicate:
1. Setup a proxy: (proxy type: SOCKS5, proxy ip address: localhost, Port 8084 (as an example)
2. have a server accessible over ssh that is running a webserver on localhost
3. setup ssh tunnel: ssh -D 8084 -f -C -q -N server-name
4. check the proxy is working for non-locahost sites in firefox by selecting the proxy and navigating to a site
5. now target the localhost website.  e.g. https://localhost.  It will not load.
6. Re-install version 7.5.1.  Perform steps above.  It now works.

Please advise if there are further useful details that can be provided here.

**Comment by erosman** [comment]
Previously: #50

**Comment by erosman** [comment]
I am discussing the issue with the founder of FoxyProxy and some or all of localhost checks will be removed in v8.4

**Comment by erosman** [comment]
It is done in v8.4
We are uploading v8.4 to AMO.
FoxyProxy Basic (same code) will be available shortly but FoxyProxy (standard) will take time due to the AMO review process.
