### ISSUE TITLE
IP addresses don't go through the proxy, previously they did

### ISSUE THREAD

**Issue by mcbyte-it** [foxyproxy/browser-extension#66]
I just got the new version today, and immediately it broke my workflow to access ip addresses over the proxy.

Check screenshot:
![image](https://github.com/foxyproxy/browser-extension/assets/3248742/474e9d5c-3297-41cf-837a-f3c72e87efc9)

previously that same IP webapp used to work by going through the proxy, and although I have no rules to exclude this address it simply don't go through.

if I configure Firefox with the same proxy and no rules, the application works as expected.

Hope you can fix the issue

Thanks

**Comment by erosman** [comment]
192.168.0.0/16 is set no not be proxied in FoxyProxy 8.
The issue of local network proxy bypass is discussed in #50

**Comment by erosman** [comment]
I am discussing the issue with the founder of FoxyProxy and some or all of localhost checks will be removed in v8.4

**Comment by erosman** [comment]
It is done in v8.4
We are uploading v8.4 to AMO.
FoxyProxy Basic (same code) will be available shortly but FoxyProxy (standard) will take time due to the AMO review process.
