### ISSUE TITLE
"Settings are controlled by another extension" since last update

### ISSUE THREAD

**Issue by jbdrucker** [foxyproxy/browser-extension#68]
Hello,

I'm on a corporate computer, unable to modify the proxy settings from Firefox' setting panel.
But Foxyproxy used to be able to circumvent this, and I was able to set my own proxy settings (which is very useful in a lab environment).

Since the last update, Foxyproxy's icon appears with a red cross on it, and the message "Settings are controlled by another extension".

Normal behaviour or functionality regression, I let you decide, but that was very useful for me.

**Comment by erosman** [comment]
There is another extension that is setting proxies.
Having 2 extension doing the proxying would create a conflict.

Can you not disable the other extension?

**Comment by jbdrucker** [comment]
The thing is, there's none, or it's always been there and hasn't bothered foxyproxy up until now. But it's not something I installed myself (see: general proxy settings greyed out)

**Comment by erosman** [comment]
Have you enabled "Private Browsing Permission"?
On Firefox, users must enable "Run in Private Windows", as it is required by Firefox for proxy settings.

**Comment by jbdrucker** [comment]
It is enabled.

**Comment by erosman** [comment]
Please go to `about:preferences`
What does **Network Settings** (bottom of the page) say?

**Comment by jbdrucker** [comment]
> Please go to `about:preferences`
> What does **Network Settings** (bottom of the page) say?

The network settings are greyed out

> I have a guess about the reason.
> FoxyProxy 7 didn't check if "Settings are controlled by another extension".
> FoxyProxy 8 does.
> There are parts of the FoxyProxy 8 that can run into error if "Settings are controlled by another extension".
> We have to check it first.

That might be exactly that.

**Comment by erosman** [comment]
It is done in v8.4
We are uploading v8.4 to AMO.
FoxyProxy Basic (same code) will be available shortly but FoxyProxy (standard) will take time due to the AMO review process.
