### ISSUE TITLE
Lost all settings and proxy list

### ISSUE THREAD

**Issue by annaparker** [foxyproxy/browser-extension#69]
Hello! The v8.2 vanished my settings and all proxies. How to restore them easily? Thank you.

**Comment by erosman** [comment]
Please note https://github.com/foxyproxy/browser-extension/issues/53#issuecomment-1848282804

**Comment by 0xquad** [comment]
Hi. I've followed the refered comments and tried the one-liner. What if it returns nothing? I don't have any Sync feature enabled (on purpose). How is it possible to export the settings in the older 7.x format? Thanks!

**Comment by annaparker** [comment]
Didn't help me, but downgrade worked and all settings back to track:
https://addons.mozilla.org/firefox/downloads/file/3616824/foxyproxy_standard-7.5.1.xpi

Also I suggest to disable auto update of that extension.

**Comment by erosman** [comment]
> Hi. I've followed the refered comments and tried the one-liner. What if it returns nothing? I don't have any Sync feature enabled (on purpose). How is it possible to export the settings in the older 7.x format? Thanks!

Did you try it from the Dev Tools in the FoxyProxy Options page (not a normal tab page)?

**Comment by erosman** [comment]
@BrandtnerKPW That was a very good catch. Thank you.
There is an oversight in migrating the data from the older version.
I will prepare an update.
