### ISSUE TITLE
FoxyProxy 8.3 - Don't capture requests from Burp Suite Proxy and Postman

### ISSUE THREAD

**Issue by skalvin** [foxyproxy/browser-extension#71]
FoxyProxy 8.3 - Don't capture requests from Burp Suite Proxy and Postman

- The new Interface of the Tool is very bad
- The Orange Color very bad
- The old Interface is more simple

**Comment by erosman** [comment]
I am discussing the issue with the founder of FoxyProxy and some or all of localhost checks will be removed in v8.4

**Comment by erosman** [comment]
It is done in v8.4
We are uploading v8.4 to AMO.
FoxyProxy Basic (same code) will be available shortly but FoxyProxy (standard) will take time due to the AMO review process.
