### ISSUE TITLE
UI for hosts added via "Quick Add"?

### ISSUE THREAD

**Issue by elfez** [foxyproxy/browser-extension#73]
While adding back the few hosts that go through a proxy I found the "Quick Add" button which seems to work well. My only issue with this is that I can't actually seem to find anywhere in the settings where added hosts can be managed. The obvious place for me would be under the relevant proxy in the "Proxies" tab, but there is nothing there. Nor can I find them anywhere else (though I have an astonishing ability to look straight at something and not see it).

Am I being blind or is the UI for this missing?

**Comment by erosman** [comment]
The process for Quick Add from the toolbar popup is:

- Select the target proxy from the select drop-down
- Click Quick Add

Please note that URL must start with `http/https/file` (not possible for internal browser pages).

If you go to the Options page (reload if already open), it should appear under the target proxy.

This is the one I did just now from `https://example.com/`

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/b683011f-caa8-4721-8d3f-3c655b7e3be6)

**Comment by elfez** [comment]
Weird, that second bit in the options page does not appear for me. Only ones I explicitly add on the proxy tab appear underneath the proxy. I'll do some more experimenting next week and see if I'm doing something wrong.

**Comment by elfez** [comment]
Reinstalled it and it all seems to work fine. Clearly a gremlin in the system.
