### ISSUE TITLE
Default title should be hostname:port as in 7.x

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/browser-extension#74]
From support email:

"please change the hint text from ip:port back to proxy name. The current FoxyProxy 8.2 hint text is useless. What information can be retrieved from the ip:port text? Am I supposed to remeber all my proxies' IPs and ports?"

@erosman  i suppose the user is talking about the _title_. In this example, title should be foo.bar:3128:

<img width="1161" alt="image" src="https://github.com/foxyproxy/browser-extension/assets/5875610/bb026d44-3ad2-4021-b171-13ab63b64dc9">

**Comment by erosman** [comment]
If the entry doesn't have a **Title**, it will be shown as **hostname:port** in the proxy header and in the toolbar popup.
In your example, it will be `foo.bar:3128`

What is the user suggesting to do?

**Comment by ericjung** [comment]
This is my guess

![title](https://github.com/foxyproxy/browser-extension/assets/5875610/ae1a41dd-b5c2-40b8-bfce-b3f79003edb7)

**Comment by erosman** [comment]
Once you SAVE, and refresh, that will be filled.
I will make it fill it before refresh as well.

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/4dd336a5-7a19-43ae-b277-42d6236e3dd8)

**Comment by erosman** [comment]
It is done in v8.4
We are uploading v8.4 to AMO.
FoxyProxy Basic (same code) will be available shortly but FoxyProxy (standard) will take time due to the AMO review process.
