### ISSUE TITLE
Per-proxy DNS Proxying

### ISSUE THREAD

**Issue by pschmitt** [foxyproxy/browser-extension#75]
In previous FoxyProxy version it used to be possible to decide on a per-proxy basis where the DNS resolution of a given endpoint would take place.

With v8+ this is now a global option.

Are there any plans to re-enable this feature?

**Comment by erosman** [comment]
please note that Proxy DNS option is only available for socks proxies (not other types of proxies).

**Comment by ericjung** [comment]
We could move “Proxy DNS” to each individual proxy setting as it was in 7.x.

**Comment by erosman** [comment]
Is the purpose to request DNS from some SOCKS and not others?

For example, when "Proxy by Patterns" is enabled ...

- if matches SOCKS A then DNS via that proxy
- if matches SOCKS B then DNS through normal UPD

**Comment by pschmitt** [comment]
> Is the purpose to request DNS from some SOCKS and not others?

Yes. In my case I need to access specific hosts whose DNS entries are not public and only resolvable through a proxy. Then  I happen to also have the inverse case where the DNS entries are public (but not published on the the "private DNS") and the URLs can only be accessed through the proxy. (It's weird, I know...).

In the past (v7) we tackled this by having 2 proxies defined: one with remote resolution and one without it + specific patterns.

**Comment by erosman** [comment]
Fair enough.
It will be done.

**Comment by erosman** [comment]
### 8.7
Changed the global Proxy DNS to per-proxy setting

Beta updated on repo for testing.

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.

**Comment by pschmitt** [comment]
Thanks a lot!

**Comment by mb** [comment]
Cross linking https://bugzilla.mozilla.org/show_bug.cgi?id=1741375#c17, because Firefox might enable DNS over SOCKSv5 by default soon and it might affect this setup.
