### ISSUE TITLE
FoxyProxy 8.2 Breaks BurpSuite DNS

### ISSUE THREAD

**Issue by ACK-J** [foxyproxy/browser-extension#78]
After the 8.2 update when using FoxyProxy and BurpSuite you can no longer use the BurpSuite "Request in browser" feature.
![image](https://github.com/foxyproxy/browser-extension/assets/60232273/66fb3527-4c36-4a53-932b-d3a5242982b3)
AS shown below the "http://burpsuite" hostname could not be resolved.
![image](https://github.com/foxyproxy/browser-extension/assets/60232273/cb9c21a9-dff8-4d7c-a663-07242345777b)
However, if you disconnect from foxyproxy and manually configure firefox to proxy through BurpSuite  "http://burpsuite" is resolved as expected.

**Comment by erosman** [comment]
It is already sorted since v8.4
Check [About](https://foxyproxy.github.io/browser-extension/src/content/about.html) for more information.
