### ISSUE TITLE
Local IP forwarding does not work after update.

### ISSUE THREAD

**Issue by R0Z-Z** [foxyproxy/browser-extension#79]
Hello,

I had been using foxyproxy to access few local network addresses starting with 192.168. by dynamic forwarding through local SOCKS5 proxy. Now with 8.2 they do not work anymore. :/ I checked specific proxy's default exclude rules, they were as I left them (off), but somehow they got ineffective. I have no global excludes.

By the way, showing connected proxy activity in patterns mode over the foxyproxy icon was a nice feature, why change it with a static one? It was actually a good indicator. Pity :/

Hope you fix it soon.
Thank you for your time.

**Comment by ericjung** [comment]
It is fixed, please update to 8.4 or above.
