### ISSUE TITLE
Support OpenVPN profile?

### ISSUE THREAD

**Issue by Kieaer** [foxyproxy/browser-extension#8]
I am using NordVPN.
NordVPN is slowly blocking http/https/socks5 proxies and forcing their browser extensions.
As of 2 months ago, the manual proxy stopped working.
No other browser extensions or external programs have a URL whitelist feature.

**Comment by ericjung** [comment]
Do you have a link to anything from NordVPN about this? If they still require use of their browser extension, it is very very likely the browser is using their proxy servers.

**Comment by Kieaer** [comment]
https://nordvpn.com/en/blog/removing-http-proxies/

**Comment by mjpieters** [comment]
You can use their socks5 proxies instead, https://nordvpn.com/blog/socks5-proxy/

**Comment by ericjung** [comment]
see also https://github.com/foxyproxy/browser-extension/issues/15
