### ISSUE TITLE
8.2: Short hostnames not proxied

### ISSUE THREAD

**Issue by ceeeekay** [foxyproxy/browser-extension#80]
Quite a few of the hosts I use via proxy have short hostnames, but since the update are not even being passed to the proxy, either HTTP or SOCKS, unless they contain a dot in the name. This is visible in the logs as there is no `Type` entry for the failed attempts.

Simple proxy pattern: `Include \S+`

Results: 
* http://some-host - miss
* http://some-host.fqdn.org - hit
* http://some-host. - hit

Cheers.

**Comment by erosman** [comment]
Plain hostnames (no dots) were regarded as local network and bypassed in v8.
The localhost, private local network pass-through was reverted in v8.4 on Firefox.
Check [About](https://foxyproxy.github.io/browser-extension/src/content/about.html) for more information.

FoxyProxy Basic (same code) v8.6 is available to download.
FoxyProxy (Standard) v8.6 is awaiting review by AMO and will be available soon.

**Comment by rodajc** [comment]
Is there a workaround for this issue until there is a solution? This issue renders the add-on unusable for me as the proxy needs to use an SSH tunnel running on localhost (no dots whatsoever).

**Comment by erosman** [comment]
FoxyProxy 8.6 is already available as Basic & Standard.
You can upgrade to v8.6.

**Comment by rodajc** [comment]
> You can upgrade to v8.6.

The automatic update to v8.6 caused the problem this morning...

**Comment by erosman** [comment]
@rodajc Please see if this helps: https://github.com/foxyproxy/browser-extension/issues/76#issuecomment-1849732560

**Comment by rodajc** [comment]
Tried everything. Nothing helps. I'm going to try and downgrade if possible at all.

**Comment by rodajc** [comment]
My problem is not related to the dots nor to v8.2. I'll open a separate issue.

**Comment by ceeeekay** [comment]
Short hostnames in 8.6 work for me - thanks :)
