### ISSUE TITLE
Problem with 'local' tld and domains in 8.6

### ISSUE THREAD

**Issue by vx-github** [foxyproxy/browser-extension#82]
After the update to 8.2 FoxyProxy Standard for Firefox and not soon after to 8.6, I got problems with URLs that contained `local` in the hostname part of the URL.

So I rolled back to 7.5.1 and created a proxy with the follow (White) paterns:
- (wildcard) *.local.nl
- (wildcard) *.domain.local
- (wildcard) *.domain.nl

When testing the following URLs:
- https://test123.local.nl/
- https://test123.domain.local/
- https://test123.domain.nl/
... all of them where send to the proxy I specified (according to the logging).

Then I did an upgrade to 8.6, and tested the same URLs (did a Firefox restart in between). Now only the `https://test123.domain.nl/` was send to the proxy and the URLs that contained `local`were not.

I consider this a bug since our organization uses `.local` domains for internal use (unfortunately) and this tld and domains were still working on 7.5.1.

**Comment by erosman** [comment]
Are you using "Proxy by Patterns" or individual proxy?
Can you post a screenshot of the patterns that you have set for the above domains in FoxyProxy 8?

**Comment by vx-github** [comment]
I used "Proxy by Patterns" (like I used "Use Enabled Proxies By Patterns and Order" in 7.5.1).

Screenshot attached:
<img width="1220" alt="Screenshot 2023-12-12 at 14 20 36" src="https://github.com/foxyproxy/browser-extension/assets/1324946/d101cde3-ce84-46f7-8992-ee151cc24c24">

**Comment by erosman** [comment]
Does the Log have any useful information?

Also ...

- Open a new tab
- Open the Developer Tools (F12)
- Go to the Network tab
- Enter `https://test123.local.nl/` in the address-bar
- Check the result

**Comment by vx-github** [comment]
The logging of FoxyProxy shows which URL request are send to the proxy and which are not (mentioned in the issue). No other usefull info.

The used URLs aren't supposed to work. they are constructed so I can see if the are passed to the proxy (seen in the FoxyProxy logging). The result in the browser also gives  a clue if a URL is tried to (DNS) resolve or if it is passed to the proxy and the proxy cannot find it.

I rolled back to 7.5.1 and for every test I need to upgrade to 8.6 and roll back again to 7.5.1 (to be able to work again). So you last 'Also ...' request will be done later.

**Comment by vx-github** [comment]
<img width="1222" alt="Screenshot 2023-12-12 at 16 07 58" src="https://github.com/foxyproxy/browser-extension/assets/1324946/5e905220-658d-4dae-936b-d146470b3c47">

**Comment by erosman** [comment]
The error shows DNS error. Firefox cant resolve the NS record for the domain.
The DNS is not something that FoxyProxy handles. It is handled by the browser.

Have you enabled DoH (DNS over HTTPS)?
Have you enabled Proxy DNS? (although I cant see that affecting the outcome)
Have you tried `nslookup` in the MacOS terminal?
```
nslookup test123.local.nl
```

**Comment by vx-github** [comment]
I made a typo in the last test, so the outcome did not reflect the problem. I will post a new screenshot.

**Comment by erosman** [comment]
Are you still having issue with the latest release?

**Comment by vx-github** [comment]
@erosman I updated Firefox to 121.0 and FoxyProxy to 8.8 and I cannot reproduce the original problem anymore and a quick test shows everything is working as expected again.
