### ISSUE TITLE
Proxy Service does nothing - even with "all pattern" in 8.6

### ISSUE THREAD

**Issue by Nitrousoxide** [foxyproxy/browser-extension#84]
I have a rule setup to proxy **any** traffic to a proxy server on the local network.  The log is not picking up any traffic as being routed through that proxy.

![image](https://github.com/foxyproxy/browser-extension/assets/1363931/e312d7e8-8460-47c3-8832-5352f1663a96)

![image](https://github.com/foxyproxy/browser-extension/assets/1363931/45c77b90-ce1c-463c-b214-6d296076072c)

It is reachable (though obviously a curl isn't going to return any useful communication)
```
~ 
❯ curl http://192.168.7.233:8888
Invalid header received from client.
```

But the logs don't even show foxyproxy even trying.

**Comment by erosman** [comment]
To make sure FoxyProxy was properly updated by the browser, try the following:

- Export FoxyProxy settings
- Remove FoxyProxy
- Restart browser to clear its cache
- Reinstall FoxyProxy
- Import your settings

**Comment by Nitrousoxide** [comment]
> To make sure FoxyProxy was properly updated by the browser, try the following:
> 
>     * Export FoxyProxy settings
> 
>     * Remove FoxyProxy
> 
>     * Restart browser to clear its cache
> 
>     * Reinstall FoxyProxy
> 
>     * Import your settings

Okay, that worked oddly enough.  I'm going to close this issue.
