### ISSUE TITLE
Please deprecate automatic release notes

### ISSUE THREAD

**Issue by detuur** [foxyproxy/browser-extension#86]
From what I can tell, FoxyProxy is entering a period of renewed active development, which is great news for my favourite proxy add-on, which I use across a variety of devices. Unfortunately, FoxyProxy still automatically displays release notes after updates. This is very poor UX, given that Firefox will auto-update add-ons in the background. So once FoxyProxy updates, it will immediately spawn a tab for its release notes and steal focus, regardless of whether you're reading a blog, typing out a PR, trying to follow your colleague's explanation on a video call, or indeed even presenting at a meeting.

I don't consider an update to FoxyProxy to be breaking news. Even for the add-ons that I'm very invested in, I don't want them to interrupt my work. Update pages are simply way too intrusive for their purpose, and that purpose can easily be supplanted by (opt-in) e-mail lists, or even a little banner in the FoxyProxy UI if it's something truly important.

At the very least, this behaviour should be opt-in.

**Comment by erosman** [comment]
The reason for showing the Help document (not the release note) is to remind users to read the Help since there are many changes in the new v8 release of FoxyProxy.

There have been many queries about features that are already documented in the Help.

This behavior is temporary and will be changed once most users have upgraded to v8.

**Comment by erosman** [comment]
v8.7
Removed Help document display on install/upgrade

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.
