### ISSUE TITLE
localhost socks5 proxy stopped working

### ISSUE THREAD

**Issue by rodajc** [foxyproxy/browser-extension#87]
After an automatic update to v8.6 my socks5 proxy through localhost stopped working.
I don't know which version I was on before the update.
This issue renders the add-on unusable for me as the proxy needs to use an SSH tunnel running on localhost.
I'm using firefox for android. Are there any logs in android?

**Comment by erosman** [comment]
Was https://github.com/foxyproxy/browser-extension/issues/70#issuecomment-1852364925 any help?

**Comment by rodajc** [comment]
I hope so too.

Why is a working version automatically replaced by a version that doesn't work? Why is the user not involved?

When is v8.7 due? What are the options meanwhile?

**Comment by erosman** [comment]
> **Firefox on Android**
> Support is experimental and based on user feedback.

FoxyProxy v8 has PAC support (was in v3 but was missing in v4-7).
It was working in FoxyProxy v7 because it didn't have PAC support.

The PAC support requires `proxy.settings` and the API is not yet supported in Firefox for Android.
We have been working on a workaround in FoxyProxy to make it work on Firefox for Android.

See also: [Bug 1725981: Support proxy.settings API on Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1725981)

> When is v8.7 due? 

Soon... I am working on it.

**Comment by maksloboda** [comment]
> > **Firefox on Android**
> > Support is experimental and based on user feedback.
> 
> FoxyProxy v8 has PAC support (was in v3 but was missing in v4-7). It was working in FoxyProxy v7 because it didn't have PAC support.
> 
> The PAC support requires `proxy.settings` and the API is not yet supported in Firefox for Android. We have been working on a workaround in FoxyProxy to make it work on Firefox for Android.
> 
> See also: [Bug 1725981: Support proxy.settings API on Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1725981)
> 
> > When is v8.7 due?
> 
> Soon... I am working on it.
> 
> > What are the options meanwhile?
> 
> Can you try and see if you can install v7.5.1 and disable update? https://addons.mozilla.org/firefox/addon/foxyproxy-standard/versions/

Same issue, cant figure out how to install old addon version on android. Can you please add a "legacy" version to the addon store?

**Comment by erosman** [comment]
> Same issue, cant figure out how to install old addon version on android. Can you please add a "legacy" version to the addon store?

FoxyProxy 7.5.1 is available on AMO, however, I couldn't get it to install in Firefox for Android (or Nightly).
It would download it but wouldn't open it.
I am asking Mozilla and will post as soon as they reply.

**Comment by erosman** [comment]
I have posted the beta & older version installation guide to https://github.com/foxyproxy/browser-extension/issues/60#issuecomment-1855966440

**Comment by rodajc** [comment]
How do I enable debug menu in Firefox for Android?

**Comment by erosman** [comment]
> How do I enable debug menu in Firefox for Android?

Sorry...my mistake.
You can enable the Debug menu in Firefox for Android *the same way as in Nightly), but it doesn't give you the option to "Install add-on from file" :man_facepalming:

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.

**Comment by rodajc** [comment]
Tried Foxy Proxy Basic v8.7 and working.

Good job! I really missed it.

Thanks a lot.
