### ISSUE TITLE
Localized text buttons covers icon buttons

### ISSUE THREAD

**Issue by VoinNochi** [foxyproxy/browser-extension#88]
Greetings!
Localized buttons with text are being displayed over buttons with icons.
![firefox_VMjTGCrbsF](https://github.com/foxyproxy/browser-extension/assets/39955225/3b96b9df-4cee-41c7-845e-841f6a5a5a26)

**Comment by erosman** [comment]
Thank you for the report.

Changed to ➕ with mouse-over title for v8.7

![image](https://github.com/foxyproxy/browser-extension/assets/6458876/e39401cb-dcb2-4aeb-844b-22f84f60c105)

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.
