### ISSUE TITLE
Add an option to spoof timezone in tabs where proxy is enabled [feature request]

### ISSUE THREAD

**Issue by selivan** [foxyproxy/browser-extension#90]
Some sites detect using proxy by comparing browser timezone and IP geolocation. Indeed, Astana timezone with Netherlands IP address looks suspicious.

I suggest to add on option to proxy configuration: spoof timezone to given one in tabs, where tab URL matches proxy pattern, or if the proxy is enabled globally.

Extensions spoofing timezone exist for both Firefox and Chrome, so it should be doable.

**Comment by erosman** [comment]
Spoofing timezone in Tabs is achieved by injecting a script into the page and run some JavaScript. A userscript can perform a similar action.

Dealing with the content of a page is beyond the scope of a proxying extension which deals with the web request before it reaches a tab.

**Comment by selivan** [comment]
@erosman I agree, this is beyond a scope of proxying extension. But it would be really useful for people, who use 
FoxyProxy in conjunction with other tools to circumvent censorship.

**Comment by erosman** [comment]
There are other considerations.

Many sites prevent injection of scripts into their page by extensions. Any site that is interested in identifying users, would probably do that.
Therefore, such feature will not work in those sites.

There is [vytal-extension](https://github.com/vytal-io/vytal-extension) which works without injecting a script but that does not work in Firefox.

**Comment by erosman** [comment]
In MV2, CSP affects extension content scripts and API. There are talks about changes in MV3.

See also:

- [Bug 1411641: CSP 'sandbox' directive prevents content scripts from matching, due to unique origin, breaking also browser features](https://bugzilla.mozilla.org/show_bug.cgi?id=1411641)
- [w3c/webextensions](https://github.com/w3c/webextensions/labels/topic%3A%20csp)

**Comment by selivan** [comment]
> There is [vytal-extension](https://github.com/vytal-io/vytal-extension) which works without injecting a script but that does not work in Firefox.

Thank you, I'll look into it. Shame it doesn't work on Firefox.
