### ISSUE TITLE
Add a record of which pattern was hit in the log

### ISSUE THREAD

**Issue by DNACore** [foxyproxy/browser-extension#91]
This will make it clearer how the patterns hit.

**Comment by erosman** [comment]
Log is generated directly from [webRequest.onBeforeRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest) and such data is not available.

**Comment by erosman** [comment]
**v8.7**
Added matching pattern to the Log display when in "Proxy by Patterns" mode

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.
