### ISSUE TITLE
Integrated tester incorrectly wrong results

### ISSUE THREAD

**Issue by TheNec** [foxyproxy/browser-extension#92]
Hello. I was one of the guys with the update problem (btw. 8.6 doesn't solve it automatically).

I needed to downgrade, export, update, import and now the proxies and the settings are back but the regexes (edit: and wildcards) do not work as they seem to be converted wrong. Luckily I only had one regex by me which could be recreated fast but the automatically created also don't work.

Edit: I found the problem(s)

1. My regex was wrong in the exported file from the old version which is a bit curious because I'm sure it worked before...
2. The import adds slashes to the end of each pattern which results in mydomain.com/index working but mydomain.com not!

Thanks for FoxyProxy and kind regards! :D

PS The Tester result symbol should flash or something when consecutive wrong or correct tests occur and it would be cool if the patterns would work without a http(s) at the beginning like before

**Comment by erosman** [comment]
> The import adds slashes to the end of each pattern which results in mydomain.com/index working but mydomain.com not!

FoxyProxy v7 had only hostname matching.
When tested against a URL, the slashes were added.

Although Firefox address-bar shows `example.com`, if you copy it, it becomes `https://example.com/`
There is always a forward slash at the end of the host.

> it would be cool if the patterns would work without a http(s) at the beginning like before

it would work but it would be better to be more precise in the patterns.
All these would work for `mydomain.com`

**Wildcard**
- `mydomain.com`
-  `://mydomain.com/` (more precise)

**Regular Expression**
- `mydomain\.com`
-  `^[^:]+://mydomain\.com/` (more precise)

Please check the included Help for more information.

**Comment by TheNec** [comment]
> 
> Although Firefox address-bar shows `[example.com](http://example.com)`, if you copy it, it becomes `https://example.com/` There is always a forward slash at the end of the host.
> 

I know but shouldn't the tester then ignore the missing slash at the end of the url or at least add a hint or something? Because if you say FoxyProxy still works the tester shows a red error x when it is missing.

> 
> **Wildcard**
> 
>     * `[mydomain.com](http://mydomain.com)`
> 
>     * `://[mydomain.com/](http://mydomain.com/)` (more precise)
> 
> 
> **Regular Expression**
> 
>     * `mydomain\.com`
> 
>     * `^[^:]+://mydomain\.com/` (more precise)
> 

This may be more precise but would not work for hosts/subdomains which could cause a leakage!

**Comment by erosman** [comment]
> I know but shouldn't the tester then ignore the missing slash at the end of the url or at least add a hint or something? 

Firefox doesn't show the slash but it is there.
The tester can only test what is given and can not guess.
There are many patterns that don't require  a slash at the end.

> This may be more precise but would not work for hosts/subdomains which could cause a leakage!

Wildcard: `://*.mydomain.com/` (more precise with possible subdomains)

-  `mydomain.com` also works but can catch `https://mydomain.com.blog.net/`
-  `mydomain.com/` also works but can catch `https://example.com/mydomain.com/`
-   `*.mydomain.com/` also works but can catch `https://example.com/hello.mydomain.com/`
