### ISSUE TITLE
basic functionality no working any more please fix

### ISSUE THREAD

**Issue by NearestWater262** [foxyproxy/browser-extension#94]
I cannot get anything to work and it is frustrating me to tears. I am on firefox.

I completely uninstalled and reinstalled it and still my basic socks5 proxies dont work anymore

All I do is just add a new proxy, select socks5, add domain and port, then select it from the drop down but still it does not proxy. If i did this on the old version, simple process, then it would just work fine. But now it doesn't work.

Can you please go back to the old code? It was working fine and now it's not!!

**Comment by erosman** [comment]
> I cannot get anything to work 

Please provide more information.
What is the OS?

> Can you please go back to the old code?

You can downgrade to v7 if you wish.
Please check https://github.com/foxyproxy/browser-extension for instructions.

**Comment by NearestWater262** [comment]
@erosman it doesnt work on linux or on android, on anything. I cannot downgrade on mobile so im stuck now.

**Comment by erosman** [comment]
There is a problem on Android and it is discussed in #60
It should be fixed in the next release.
It is possible to downgrade using Nightly on Android.

AFA Linux, please tell us more about the issue.

**Comment by NearestWater262** [comment]
understood about android, thanks

on linux I am using a variant of firefox called Mullvad browser. It works on Librewolf but not on Mullvad Browser. But, it's fine if you dont fix. I will just use the old version.

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.
