### ISSUE TITLE
Doesn't work on Firefox 120.1.0 on Redmi Note 7

### ISSUE THREAD

**Issue by brano256** [foxyproxy/browser-extension#96]
Firefox version: 120.1.0, Android phone edition: Redmi Note 7, sold in China mainland

**Comment by erosman** [comment]
There is a problem on Android and it is discussed in #60
It should be fixed for v8.7.

**Comment by erosman** [comment]
Foxy Proxy v8.7 uploaded to AMO.
Basic is available now and standard will be after it is reviewed by AMO.
