### ISSUE TITLE
Cannot disable/switch proxy via toolbar

### ISSUE THREAD

**Issue by aik** [foxyproxy/browser-extension#98]
Switching proxies does not work. I simplified the config to this: I have 1 proxy configured, with "\S+" (==everything) and I wanted to manually switch between proxy/noproxy, via the toolbar. However the selection does not work and my proxy is always selected. Is there a fix for it, I mean, besides restarting the browser every time?
Addon v8.7, Firefox 118.0.1 (64-bit), Linux Fedora 38.

**Comment by erosman** [comment]
>  I wanted to manually switch between proxy/noproxy

Do you only have 1proxy in your set-up?
Does the popup show:

- Proxy by Patterns
- Disable
- Proxy-x

In this case, the on and off can be achieved by selecting between "Disable" & "Proxy-x".
There is no need to have patterns.

Otherwise, please tell us more about your set-up.
