### ISSUE TITLE
Sync still not working (v. 8.7)

### ISSUE THREAD

**Issue by Doc73** [foxyproxy/browser-extension#99]
No way!
I just installed Firefox 122 beta on my main PC, alongside Firefox ESR and Firefox Stable, and I can confirm that syncing still doesn't work.

In truth, since this plugin went to version 8, I have never been able to see the synchronization working and I have always had to resort to manual imports, both on Firefox and on Chrome.

In short, the proxy rules just don't show up! :cry:

**Comment by erosman** [comment]
Are you syncing between v8 instances?

**Comment by Doc73** [comment]
Yes, all instances now are on v. 8, in all my PCs and in all my browsers

**Comment by erosman** [comment]
I assume Firefox sync is also on.

Please try:

- Go to the FoxyProxy Options page
- Open the Dev Tools (F12)
- Go to the Console tab
- Type the following and hit ENTER

```js
browser.storage.sync.get().then(console.log)
```

What is the result in each of the synced Firefox browsers?

**Comment by Doc73** [comment]
@erosman 
Yes, Firefox sync is enabled!
I already did this test! This command give some result and the next command of your tutorial downloads the json.

**Comment by erosman** [comment]
Can you post a screenshot?

Is it possible to post the settings? 
_(you can remove the private information before posting)_

**Comment by Doc73** [comment]
![Schermata del 2023-12-20 13-29-08](https://github.com/foxyproxy/browser-extension/assets/1306260/156bfaa6-98ee-4039-8045-57421d03110d)
![Schermata del 2023-12-20 13-29-18](https://github.com/foxyproxy/browser-extension/assets/1306260/1a5998a0-2b5c-4aa8-8117-1b8d6352f118)

**Comment by Doc73** [comment]
From another firefox, where I imported the settings manually

![Schermata del 2023-12-20 13-30-33](https://github.com/foxyproxy/browser-extension/assets/1306260/23e16e18-f532-4cf7-b6e2-3886dd68f2e6)

**Comment by erosman** [comment]
Please let me know...
- Is "Enable Sync" on in all of them?
- Can you show a screenshot of `browser.storage.sync.get().then(console.log)`?
- Do the Privoxy servers and TOR servers have the same hostname:port?

**Comment by Doc73** [comment]
> Please let me know...
> 
>     * Is "Enable Sync" on in all of them?
> 
Yes

>     * Can you show a screenshot of `browser.storage.sync.get().then(console.log)`?

![Schermata del 2023-12-20 14-12-06](https://github.com/foxyproxy/browser-extension/assets/1306260/3c4f9415-0cbd-48af-a2ba-aebf94ee7be9)

> 
>     * Do the Privoxy servers and TOR servers have the same hostname:port?

Both are on localhost, but the second one is disabled and I left it just as a reminder. Ultimately, these are the same configurations as in v. 7.5, imported manually when you switched to version 8

**Comment by Doc73** [comment]
Of course, I could do a manual import of the settings, but I think it is more useful now to solve this problem. Until now, I have never seen, since the v. 8, an automatic synchronization!

**Comment by erosman** [comment]
The screenshot shows the sync data from v7 & v8.

- Use the code on [Settings disappeared after the upgrade to v8](https://github.com/foxyproxy/browser-extension) to create a backup file of the browser sync data
- If needed repeat for all instances of Firefox
- Run the following in the **FoxyProxy Options page -> Dev Tools**, which would clear/delete all the sync data
```js
browser.storage.sync.clear()
```
- In one of the Firefox instances, click SAVE to initiate the creation of new sync data

Let's see how that works out.

**Comment by Doc73** [comment]
I'm sorry, but really I must clear ALL sync data????

**Comment by erosman** [comment]
Alternatively, post the sync data so that I can check it.
_(you can remove the private information before posting)_

**Comment by Doc73** [comment]
```
{
  "0": {
    "active": true,
    "title": "Privoxy",
    "type": "http",
    "hostname": "127.0.0.1",
    "port": "8118",
    "username": "",
    "password": "",
    "cc": "",
    "city": "",
    "color": "#66cc66",
    "pac": "",
    "pacString": "",
    "proxyDNS": true,
    "include": [
SOME RULES
  ],
    "exclude": []
  },
  "1": {
    "active": false,
    "title": "Rasp Privoxy",
    "type": "http",
    "hostname": "XXXXX",
    "port": "8118",
    "username": "",
    "password": "",
    "cc": "",
    "city": "",
    "color": "#df46df",
    "pac": "",
    "pacString": "",
    "proxyDNS": true,
    "include": [],
    "exclude": []
  },
  "2": {
    "active": false,
    "title": "Rasp Tor",
    "type": "socks5",
    "hostname": "XXXXX",
    "port": "9050",
    "username": "",
    "password": "",
    "cc": "",
    "city": "",
    "color": "#6db9cc",
    "pac": "",
    "pacString": "",
    "proxyDNS": true,
    "include": [
SOME RULES
    ],
    "exclude": []
  },
  "3": {
    "active": false,
    "title": "Tor",
    "type": "socks5",
    "hostname": "127.0.0.1",
    "port": "9050",
    "username": "",
    "password": "",
    "cc": "",
    "city": "",
    "color": "#cc1d0d",
    "pac": "",
    "pacString": "",
    "proxyDNS": true,
    "include": [
SOME RULES
    ],
    "exclude": []
  },
  "ijl831510855683809": {
    "active": true,
    "address": "127.0.0.1",
    "blackPatterns": [],
    "color": "#66cc66",
    "index": 0,
    "pacURL": "",
    "password": "",
    "port": 8118,
    "title": "Privoxy",
    "type": 1,
    "username": "",
    "whitePatterns": [
SOME RULES
    ],
    "proxyDNS": false
  },
  "oi30qj1504593779192": {
    "active": false,
    "address": "localhost",
    "blackPatterns": [],
    "color": "#cc1d0d",
    "index": 4,
    "port": 9050,
    "title": "Tor",
    "type": 3,
    "whitePatterns": [
SOME RULES
    ],
    "proxyDNS": true,
    "username": "",
    "password": "",
    "pacURL": ""
  },
  "fzse1g1696685685691": {
    "type": 1,
    "color": "#df46df",
    "title": "Rasp Privoxy",
    "active": false,
    "address": "XXXXX",
    "port": 8118,
    "proxyDNS": false,
    "username": "",
    "password": "",
    "whitePatterns": [],
    "blackPatterns": [],
    "pacURL": "",
    "index": 2
  },
  "logging": {
    "size": 100,
    "active": false
  },
  "l7j16r1668524890608": {
    "type": 3,
    "color": "#6db9cc",
    "title": "Rasp Tor",
    "active": false,
    "address": "XXXXX",
    "port": 9050,
    "proxyDNS": true,
    "username": "",
    "password": "",
    "whitePatterns": [
 SOME RULES
    ],
    "blackPatterns": [],
    "pacURL": "",
    "index": 3
  },
  "k20d21508277536715": {
    "active": true,
    "blackPatterns": [],
    "color": "#0055E5",
    "index": 1,
    "notes": "These are the settings that are used when no patterns match a URL.",
    "title": "Default",
    "type": 5,
    "whitePatterns": [
      {
        "title": "all URLs",
        "pattern": "*",
        "type": 1,
        "protocols": 1,
        "active": true
      }
    ]
  },
  "mode": "patterns"
}
```

**Comment by erosman** [comment]
Please try the following:

- Add a new dummy proxy to one Firefox instance
- Wait for a while (sync is not immediate)
- Check if it is picked up elsewhere
- Check `browser.storage.sync.get().then(console.log)` everywhere to see if the new server was added

**Comment by Doc73** [comment]
The new dummy proxy doesn't appear elsewhere, but, just for curiosity, is this the right syntax of the json settings?
![Schermata del 2023-12-20 16-37-02](https://github.com/foxyproxy/browser-extension/assets/1306260/9d658944-8a86-4630-80ee-84a3f1a0ca9c)
This file is from the foxyproxy of my new instance of Firefox Beta, where nothing appears in settings!!!!

**Comment by erosman** [comment]
> but, just for curiosity, is this the right syntax of the json settings?

No.. that is messed up.

- `obj` was a mistake in v8.0 code as per #36, it shouldn't be there since v8.1
- it also appears that the `container` & `commands` are also messed up

Can you paste the actual above JSON here?

**Comment by Doc73** [comment]
```
{
  "mode": "pattern",
  "sync": true,
  "autoBackup": false,
  "showPatternProxy": false,
  "passthrough": "",
  "container": {
    "incognito": "",
    "container-1": "",
    "container-2": "",
    "container-3": "",
    "container-4": ""
  },
  "commands": {
    "setProxy": "",
    "setTabProxy": "",
    "quickAdd": ""
  },
  "data": [
    {
      "active": true,
      "title": "Privoxy",
      "type": "http",
      "hostname": "127.0.0.1",
      "port": "8118",
      "username": "",
      "password": "",
      "cc": "",
      "city": "",
      "color": "#add8e6",
      "pac": "",
      "pacString": "",
      "proxyDNS": true,
      "include": [
        SOME RULES
      ],
      "exclude": []
    },
    {
      "active": false,
      "title": "Tor",
      "type": "socks5",
      "hostname": "127.0.0.1",
      "port": "9050",
      "username": "",
      "password": "",
      "cc": "",
      "city": "",
      "color": "#f66151",
      "pac": "",
      "pacString": "",
      "proxyDNS": true,
      "include": [
        SOME RULES
      ],
      "exclude": []
    },
    {
      "active": false,
      "title": "Rasp Privoxy",
      "type": "http",
      "hostname": "XXX.XXX.XXX.XX",
      "port": "8118",
      "username": "",
      "password": "",
      "cc": "",
      "city": "",
      "color": "#808000",
      "pac": "",
      "pacString": "",
      "proxyDNS": true,
      "include": [],
      "exclude": []
    },
    {
      "active": false,
      "title": "Rasp Tor",
      "type": "socks5",
      "hostname": "XXX.XXX.XXX.XX",
      "port": "9050",
      "username": "",
      "password": "",
      "cc": "",
      "city": "",
      "color": "#66cdaa",
      "pac": "",
      "pacString": "",
      "proxyDNS": true,
      "include": [
       SOME RULES
      ],
      "exclude": []
    }
  ],
  "obj": {}
```

**Comment by Doc73** [comment]
```
{
  "mode": "pattern",
  "sync": true,
  "autoBackup": false,
  "showPatternProxy": false,
  "passthrough": "",
  "container": {
    "incognito": "",
    "container-1": "",
    "container-2": "",
    "container-3": "",
    "container-4": ""
  },
  "commands": {
    "setProxy": "",
    "setTabProxy": "",
    "quickAdd": ""
  },
  "data": [
    {
      "active": true,
      "title": "Privoxy",
      "type": "http",
      "hostname": "127.0.0.1",
      "port": "8118",
      "username": "",
      "password": "",
      "cc": "",
      "city": "",
      "color": "#add8e6",
      "pac": "",
      "pacString": "",
      "proxyDNS": true,
      "include": [
        SOME RULES
      ],
      "exclude": []
    },
    {
      "active": false,
      "title": "Tor",
      "type": "socks5",
      "hostname": "127.0.0.1",
      "port": "9050",
      "username": "",
      "password": "",
      "cc": "",
      "city": "",
      "color": "#f66151",
      "pac": "",
      "pacString": "",
      "proxyDNS": true,
      "include": [
        SOME RULES
      ],
      "exclude": []
    },
    {
      "active": false,
      "title": "Rasp Privoxy",
      "type": "http",
      "hostname": "XXX.XXX.XXX.XX",
      "port": "8118",
      "username": "",
      "password": "",
      "cc": "",
      "city": "",
      "color": "#808000",
      "pac": "",
      "pacString": "",
      "proxyDNS": true,
      "include": [],
      "exclude": []
    },
    {
      "active": false,
      "title": "Rasp Tor",
      "type": "socks5",
      "hostname": "XXX.XXX.XXX.XX",
      "port": "9050",
      "username": "",
      "password": "",
      "cc": "",
      "city": "",
      "color": "#66cdaa",
      "pac": "",
      "pacString": "",
      "proxyDNS": true,
      "include": [
        SOME RULES
      ],
      "exclude": []
    }
  ],
  "obj": {
    "data": [
      {
        "active": true,
        "title": "Privoxy",
        "type": "http",
        "hostname": "127.0.0.1",
        "port": "8118",
        "username": "",
        "password": "",
        "cc": "",
        "city": "",
        "color": "#66cc66",
        "pac": "",
        "pacString": "",
        "proxyDNS": true,
        "include": [
          SOME RULES
        ],
        "exclude": []
      },
      {
        "active": false,
        "title": "Rasp Privoxy",
        "type": "http",
        "hostname": "XXX.XXX.XXX.XX",
        "port": "8118",
        "username": "",
        "password": "",
        "cc": "",
        "city": "",
        "color": "#df46df",
        "pac": "",
        "pacString": "",
        "proxyDNS": true,
        "include": [],
        "exclude": []
      },
      {
        "active": false,
        "title": "Rasp Tor",
        "type": "socks5",
        "hostname": "XXX.XXX.XXX.XX",
        "port": "9050",
        "username": "",
        "password": "",
        "cc": "",
        "city": "",
        "color": "#6db9cc",
        "pac": "",
        "pacString": "",
        "proxyDNS": true,
        "include": [
          SOME RULES
        ],
        "exclude": []
      },
      {
        "active": false,
        "title": "Tor",
        "type": "socks5",
        "hostname": "localhost",
        "port": "9050",
        "username": "",
        "password": "",
        "cc": "",
        "city": "",
        "color": "#cc1d0d",
        "pac": "",
        "pacString": "",
        "proxyDNS": true,
        "include": [
          SOME RULES
        ],
        "exclude": []
      }
    ]
  }
}
```

**Comment by erosman** [comment]
Where is that from?
It appears to be from **Export** or `browser.storage.local.get().then(console.log)`.

In any case, it is fine. The `"obj": {}` shouldn't be there, but I dont think it causes a problem.

If it is in `browser.storage.local.get().then(console.log)`, you can delete it with
```js
browser.storage.local.remove('obj')
```

**Comment by Doc73** [comment]
From export

**Comment by erosman** [comment]
You can delete`obj` from you settings.

**Comment by Doc73** [comment]
Yes, I already deleted all the settings and tried to restart it from scratch, but I never get full syncs and some things are still left out.
I'll do some tests in the next few days and let you know.

**Comment by Doc73** [comment]
Here are some sad facts!

- I recreated a new, clean profile from scratch
- Since I couldn't synchronize the various browsers, I import the configuration into all the others browser
- Now four Firefoxes in two machines are identical, with three proxies inactive and one active
- I add a rule in the proxy
- After a few seconds, the rule is added automatically to another Firefox, but all the three inactive proxies disappear! :cry:

**Comment by erosman** [comment]
I am not sure where the `obj` comes from. Did you clear the previous sync data?

If you want to text, you need to do the following:

- Clear all the data in all browsers (that means the settings, as well as sync data)
- Enables sync in all browsers
- Set some values in only ONE browser & save
- Wait to see the result

**Comment by Doc73** [comment]
How can I remove ALL sync data? By creating new FF profiles?
Or is it sufficient to reset the foxyproxy data? In case, how?
I had simply reset all FoxyProxy profiles using "Restore Defaults" among the options, in all browsers, then imported a json without `obj`.

**Comment by erosman** [comment]
> How can I remove ALL sync data? By creating new FF profiles?

New profile not needed. Run this on all browsers from FoxyProxy Options page ...

```js
browser.storage.sync.clear()
```

> Or is it sufficient to reset the foxyproxy data? In case, how?

Click "Restore Defaults" and then SAVE

> I had simply reset all FoxyProxy profiles using "Restore Defaults" among the options, in all browsers, then imported a json without obj.

That is good.

**Comment by Doc73** [comment]
- `browser.storage.sync.clear()` in all browsers
- Restore Defaults" and then SAVE in all browsers
- Import right json in ONE browser
- Toggle sync in another browser --> no result! :cry:

**Comment by Doc73** [comment]
Ah!
Although I deleted the profile as you told me, from the second Firefox I downloaded the json. Well, it contains an empty `data` and always that damn `obj`!!!!

**Comment by erosman** [comment]
Restart the browser after clearing everything, to make sure its cache it cleared.

**Comment by Doc73** [comment]
No, no, no! It is not possible!!!!!
After deleting the data and restarting the browser, without having made any changes to foxyproxy, I exported the json: IT STILL CONTAINS THE `OBJ` SECTION!

**Comment by erosman** [comment]
The sync data is sent elsewhere by Firefox and then sent to other browsers from there.

You can try to clear the sync data and then do not enable sync for a while.
You can also try deleting that 'obj' and see ...

```js
browser.storage.local.remove('obj')
browser.storage.sync.remove('obj')
```

**Comment by Doc73** [comment]
Done!
Tomorrow we'll see what happens. In the meantime, thanks so much for your help!

**Comment by erosman** [comment]
Try to uninstall all Firefox instances, restart the browsers and then install again one by one, and check their storage.

**Comment by Doc73** [comment]
I can try, but that's definitely not the problem. Now I'm on the laptop, so on another machine, yet the json still contains the obsolete `obj`, which is evidently what makes syncing problematic.

In fact, I noticed that when I told you that there was only one rule left, this was the one in `data`, while all the others, including the remaining profile, had migrated to `obj`.

PS: I'm on a Debian GNU/Linux machine, therefore I can't uninstall Firefox-est without breaking the system. BTW, it will be sufficient to remove the old profile and create a new one.

**Comment by erosman** [comment]
Thank you for testing. Let em check again and see what is going wrong.

**Comment by Doc73** [comment]
Starting with a new profile, here's what I did:

1. sync with mozilla to recover all settings and plugins
2. export json from FoxyProxy --> NO `obj`
3. create some rules in FP and restart Firefox  --> export json from FoxyProxy --> NO `obj`
4. enable sync and restart Firefox  --> export json from FoxyProxy --> NO `obj`
5. open another version of Firefox and redo points 1-4 here
6. NO SYNC in the second Firefox :cry:

**Comment by erosman** [comment]
I also tested but `obj` did not appear.

I suspect, the ESR has issues.

From experience, sometimes an upgrade is partially completed and the addon ends up with some cached file from the previous version mixed with the new version. In these cases, it is best to uninstall and reinstall the extension.

See also: #73, https://github.com/foxyproxy/browser-extension/issues/76#issuecomment-1849732560

**Comment by Doc73** [comment]
Reinstalled FoxyProxy.
I imported settings in ESR, then enabled sync in Beta, but nothing has arrived yet here and lots of minutes have passed.

**Comment by erosman** [comment]
Can you make an edit in the Options page?
Any edit will do, disable a proxy for example.
The edit will cause the sync to be started on SAVE.

**Comment by Doc73** [comment]
OMG! I added a rule in one FF and after some minutes the addition went to other FF; then, I removed this rule in the latest one and... in FF beta all proxy settings are gone, except the active one!
I can't remember which one I started with.

I don't think there are issues in Sync betwenn ESR e Beta: your link is very obsolete and now ESR is at v. 115, Beta at v. 122

**Comment by erosman** [comment]
I am going to work on and hopefully improve the sync process for v8.8.

**Comment by erosman** [comment]
I found the reason.
There are conflicting information on MDN which led to the issue.


> [storage.onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged#changes)
> 
> `object`. Object describing the change. This object contains properties for all the keys in the storage area included in the [storageArea.set](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set) call, even if key values are unchanged.

> [storage.StorageArea.onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/onChanged#changes)
> 
> `object`. Object describing the change. This contains one property for each key that changed. The name of the property is the name of the key that changed, and its value is a [storage.StorageChange](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageChange) object describing the change to that item.


First one says: "all the keys in the storage area, even if key values are unchanged"
Second one says: "one property for each key that changed."

After some testing, both return ONLY the changed value, not all values. So if one proxy is changed, the `onChanged` only returns that proxy. That is the reason the sync ends up with only one proxy.

AFA I recall, the behaviour used to be like the first and I think it might have changed later (probably when the 2nd API was introduced in Firefox 101.

Now that the problem has been found, I am going to re-write the sync process.

**Comment by erosman** [comment]
I have updated the repo with the reworked sync process.

Here is a zip of the beta for testing
The beta can be tested between 2 Firefox Nightly, or 2 Chrome instances.

[foxyproxy.8.8.beta.chrome.zip](https://github.com/foxyproxy/browser-extension/files/13749475/foxyproxy.8.8.beta.chrome.zip)
[foxyproxy.8.8.beta.firefox.zip](https://github.com/foxyproxy/browser-extension/files/13749478/foxyproxy.8.8.beta.firefox.zip)

**Comment by Doc73** [comment]
@erosman Unfortunately I can't test this zip, because I can't remove official Firefox installed by default in every Debian GNU/Linux system. :cry:

**Comment by erosman** [comment]
> @erosman Unfortunately I can't test this zip, because I can't remove official Firefox installed by default in every Debian GNU/Linux system. 😢

No problem.
I don't have multiple computers to try myself.
It would be good to test it before the release.
Maybe someone else can test it.

**Comment by erosman** [comment]
v8.8 was uploaded to AMO.
FoxyProxy Basic is available now and FoxyProxy Standard will be available after the AMO review.

**Comment by erosman** [comment]
Did v8.8 fix the issue?

**Comment by Doc73** [comment]
I'm sorry, but I can do any test before Sunday.

**Comment by Doc73** [comment]
@erosman 
Ok! The plugin works well and I got sync both from Firefox Beta to Firefox Stable and from Firefox Stable to Firefox Beta.

Perhaps the only problem is the excessive slowness of the process, which also requires some browser restarts. It's a real shame, since the v. 7 was very fast.

BTW, I think you could close this issue report. Thanks!

**Comment by erosman** [comment]
> Perhaps the only problem is the excessive slowness of the process, which also requires some browser restarts. It's a real shame, since the v. 7 was very fast.

The speed shouldn't have changed.

- Every time browser starts (or background script is restarted), sync data is checked and local data updated
- Every time a change is made (SAVE from Options page), the sync `onChanged` fires and it should be passed on to the other browser instances
- The interval that changes are passed on to the other instances are controlled by the browser (not the extension)

**Comment by emoxam** [comment]
I am using firefox 128.0.3 (64-bit) from mozilla repo. And i have a flatpak installed firefox 128.0.3 (64-bit).
Long time ago i wondering can i sync my foxyproxy settings? 
I am checking 'sync' checkboxes at both of my foxyproxy and logging to both firefox with the same credentials.
I got all synced except the proxies list and patterns. My foxyproxy ix 8.9. Is syncing for proxylist working or i can only use manual importing ?

**Comment by erosman** [comment]
@emoxam If the sync between browsers works with other extensions, it should also work for FoxyProxy.

FoxyProxy sends sync data when an edit has been made. Otherwise, it would be difficult to decide which FoxyProxy settings should be synced with which one (A -> B or B -> A).

Therefore, after enabling the browser sync and the FoxyProxy sync, make a small edit to the settings that you want to be the source.

**Comment by emoxam** [comment]
Got it. Thanks. All is working.

**Comment by emoxam** [comment]
And again. Using firefox from firefox-128.0.3.tar.bz2 at home and and work, at work proxies doesn't sync. What log can i check ?

**Comment by erosman** [comment]
> What log can i check ?

### Look for sync data

1. Go to the FoxyProxy Options page
2. Open the Dev Tools (F12)
3. Go to the Console tab
4. Type the following and hit ENTER

```js
  browser.storage.sync.get().then(console.log)
```

Check the result. If there is no data, Firefox hasn't synced the data (yet).

**Comment by emoxam** [comment]
> > What log can i check ?
> 
> ### Look for sync data
> 
>     1. Go to the FoxyProxy Options page
> 
>     2. Open the Dev Tools (F12)
> 
>     3. Go to the Console tab
> 
>     4. Type the following and hit ENTER
> 
> 
> ```js
>   browser.storage.sync.get().then(console.log)
> ```
> 
> Check the result. If there is no data, Firefox hasn't synced the data (yet).

Under linux i added new proxy, but when i back to windows i don't see this proxy at the foxyproxy. What can i do ?

**Comment by emoxam** [comment]
Surely it's ON and it's working.

**Comment by erosman** [comment]
What is the result of the following?
```js
 browser.storage.sync.get().then(console.log)
```

**Comment by emoxam** [comment]
On what side ? Linux or WIndows ?

**Comment by emoxam** [comment]
![image](https://github.com/user-attachments/assets/d8d9a835-a037-4814-9517-f7b6c5e3c39c)
Linux

**Comment by emoxam** [comment]
![изображение](https://github.com/user-attachments/assets/2935dbca-89b2-4acf-b1db-764cab403557)
Windows

**Comment by erosman** [comment]
They appear to be synced i.e. have the same data.
However, they seem to have leftover data from older versions. It is possible that the old data is causing an issue.

You can delete the sync data on both machines and then regenerate them.

- Export your settings to have a backup
- Clear the data on both machines
```js
browser.storage.sync.clear()
```
- Check if they are cleared
```js
browser.storage.sync.get().then(console.log)
```
- Make an edit to one of the FoxyProxy instances
- Check if new sync data is created
```js
browser.storage.sync.get().then(console.log)
```

**Comment by emoxam** [comment]
WIndows machine rewrited with the old setting all the new settings! drama!

**Comment by erosman** [comment]
Did you clear the data on both machines?
If so, there should be no old data, unless there are other machines that you are synced with (e.g. on mobile).
